pkg/networkservicemesh/core/adapters/client_to_server.go, pkg/networkservicemesh/core/next/client.go, pkg/registry/core/adapters/discovery_client_to_server.go, pkg/registry/core/adapters/discovery_server_to_client.go, pkg/registry/core/adapters/registry_client_to_server.go, pkg/registry/core/adapters/registry_server_to_client.go, pkg/registry/core/chain/discovery_client.go, pkg/registry/core/chain/discovery_server.go, pkg/registry/core/chain/registry_client.go, pkg/registry/core/chain/registry_server.go, pkg/registry/core/next/discovery_client.go, pkg/registry/core/next/discovery_context.go, pkg/registry/core/next/discovery_server.go, pkg/registry/core/next/registry_client.go, pkg/registry/core/next/registry_context.go, pkg/registry/core/next/registry_server.go, pkg/registry/core/trace/context.go, pkg/registry/core/trace/discovery_client.go, pkg/registry/core/trace/discovery_server.go, pkg/registry/core/trace/registry_client.go, pkg/registry/core/trace/registry_server.go
Is based on #13
Please only review pkg/registry/core
=> Added registry core.

pkg/networkservice/common/roundrobin/server.go
And to set the Connection.NetworkServiceEndpoint name correctly.
=> Update roundrobin to only select if a selection has yet to be made

pkg/networkservice/common/connect/client_map.go, pkg/networkservice/common/connect/tests/server_test.go
=> Fix nil pointer exception on call ConnectServer.Request

pkg/networkservice/common/clientinfo/client.go, pkg/tools/clientinfo/clientinfo.go
Also switch to using trace.Log(ctx) in clientinfo
=> Rename clientinfoutils to clientinfo

pkg/networkservice/core/eventchannel/monitor_client.go
Make it clear when opts aren't used.
=> Minor fix to eventchannel for clarity.

.golangci.yml, pkg/networkservice/common/monitor/server_test.go
The intention was the make things simpler and easier to read and understand
by using the existing APIs rather than introducing new machinery.
=> Refactored the server_test.go to use the new adapters.

pkg/networkservice/common/updatepath/client.go, pkg/networkservice/common/updatepath/client_test.go, pkg/networkservice/common/updatepath/server.go, pkg/networkservice/common/updatepath/server_test.go, pkg/networkservice/common/updatepath/updatepath_test.go
Added tests for pkg/networkservice/updatepath
=> Add tests for updatePath chain elements 

pkg/networkservice/common/heal/client_test.go
Fix issue https://github.com/networkservicemesh/sdk/issues/126
Test didn't expect that heal might be called twice for the same connection. But that behaviour is fine.
Signed-off-by: Ilya Lobkov <ilya.lobkov@xored.com>
=> Issue #126: Flaky TestNewClient_MissingConnectionsInInit

pkg/networkservice/common/clienturl/server_test.go
Added tests for pkg/networkservice/common/clienturl
=> Add clientUrl tests

pkg/networkservice/common/filtermechanisms/client_test.go, pkg/networkservice/common/filtermechanisms/server_test.go
Added tests for pkg/networkservice/common/filtermechanisms
=> Add filterMechanisms tests

pkg/networkservice/common/updatepath/client.go, pkg/networkservice/common/updatepath/client_test.go, pkg/networkservice/common/updatepath/server.go, pkg/networkservice/common/updatepath/server_test.go
Also add unit tests to catch this case.
=> Fix panic if Request.GetConnection().GetPath() is nil.

pkg/networkservice/common/setid/client_test.go, pkg/networkservice/common/setid/server_test.go
Added tests for pkg/networkservice/common/setid package
=> Add setId tests

pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discover/server_test.go
=> Fix match order in discoverCandidatesServer

.golangci.yml, pkg/networkservice/chains/nsmgr/peertracker/server.go, pkg/networkservice/chains/nsmgr/server.go
This lays down a pattern for providing the Nsmgr chain.
=> Initial (very rough) nsmgr chain

pkg/tools/grpcoptions/grpcoptions.go
It turns out that a spiffe.TLSPeer is a persistent-ish thing, so you
want to pass it into the grpc options, not create it inside of them.
=> Update spiffe related grpc options

pkg/tools/callback/server_test.go
Pr to restore callback tests and find why they could fail.
=> Return callback tests

pkg/tools/callback/server_test.go
Reverts networkservicemesh/sdk#199
=> Revert "Return callback tests"

pkg/networkservice/common/mechanisms/kernel/server.go, pkg/tools/fs/inode_linux.go, pkg/tools/fs/inode_linux_amd64.go, pkg/tools/fs/inode_windows_amd64.go
There will still be other Linux-isms but this will get the build/test cycle working.
Signed-off-by: Frederick F. Kautz IV <fkautz@alumni.cmu.edu>
=> Fix windows build/test

pkg/networkservice/ipam/point2pointipam/server.go, pkg/networkservice/ipam/point2pointipam/server_test.go
Signed-off-by: Frederick F. Kautz IV <fkautz@alumni.cmu.edu>
=> rename point2point to point2pointipam

pkg/networkservice/common/refresh/client_test.go, pkg/tools/executils/options.go
=> Add WithEnv to exec

pkg/networkservice/core/eventchannel/monitor_connection_server.go, pkg/networkservice/core/eventchannel/monitor_server_test.go
https://github.com/networkservicemesh/sdk/issues/196
=> Fix race condition in eventchannel

pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go, pkg/networkservice/connectioncontext/dnscontext/options.go, pkg/networkservice/connectioncontext/dnscontext/server_test.go, pkg/networkservice/core/eventchannel/monitor_client.go, pkg/tools/dnscontext/const.go, pkg/tools/dnscontext/doc.go, pkg/tools/dnscontext/manager.go, pkg/tools/dnscontext/manager_test.go, pkg/tools/dnscontext/resolv_conf.go, pkg/tools/dnscontext/resolv_conf_test.go
https://github.com/networkservicemesh/sdk/issues/185
=> Create DNSContext NetworkServiceClient chain element

.github/workflows/ci.yaml
https://github.com/networkservicemesh/sdk/issues/246
=> Add go generate ./... check on CI 

pkg/tools/debug/self.go
Turns out that os.Args[0] is not necessarily the Absolute
path of the executable.  So used os.Executable instead.
=> Fix to pkg/tools/debug

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/common/authorize/client.go, pkg/networkservice/common/authorize/client_option.go, pkg/networkservice/common/authorize/client_test.go, pkg/networkservice/common/connect/tests/server_test.go
=> Authorization Client: Add possible to generate tokens

.golangci.yml, pkg/tools/opa/tokens_expired_policy.go, pkg/tools/opa/tokens_expired_policy_test.go
https://github.com/networkservicemesh/sdk/issues/51
https://github.com/networkservicemesh/sdk/issues/201 // This PR implements **2. No Tokens in path expired - none of the tokens in the chain are expired.**
=> OPA: Add tokens expired policy

.golangci.yml, pkg/tools/opa/doc.go, pkg/tools/opa/tokens_valid_policy.go, pkg/tools/opa/tokens_valid_policy_test.go
**Depends on #259**
https://github.com/networkservicemesh/sdk/issues/201 // This PR Implements **1. Tokens valid - checks the validity of some or all of the tokens in the path.**
=> OPA: Add tokens valid policy

pkg/registry/common/setmgr/server.go
Chain element to set current NSMgr.
=> Set manager chain element

.golangci.yml, pkg/tools/opa/common_test.go, pkg/tools/opa/doc.go, pkg/tools/opa/opainput.go, pkg/tools/opa/tokens_chain_policy.go, pkg/tools/opa/tokens_chain_policy_test.go, pkg/tools/opa/tokens_expired_policy_test.go, pkg/tools/opa/tokens_valid_policy_test.go
https://github.com/networkservicemesh/sdk/issues/201
This PR Implements **Token.Aud for token n in path matches Token.Sub for n+1 token in chain**
=> OPA: Add tokens chain policy

go.mod, go.sum, pkg/tools/spire/start.go
=> Remove Spiffe v1 reference

pkg/tools/opa/all_tokens_valid_policy.go, pkg/tools/opa/all_tokens_valid_policy_test.go, pkg/tools/opa/last_token_signed_policy.go, pkg/tools/opa/last_token_signed_policy_test.go
This PR Implements last of OPA policies https://github.com/networkservicemesh/sdk/issues/201
=> OPA: Add policy: all tokens in path are valid

pkg/networkservice/common/connect/server.go, pkg/networkservice/common/connect/tests/server_test.go, pkg/tools/callback/server.go, pkg/tools/grpcutils/listen_and_serve.go, pkg/tools/grpcutils/url.go
+ Allow callback from connect chain element
* Fix tcp support for connect
+ Allow to return tcp address for grpc utils.
=> Client option factory and fixes

pkg/registry/nsmreg/adapters.go, pkg/registry/nsmreg/filters.go, pkg/registry/nsmreg/server.go
=> NSM registry chain element

pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_options.go, pkg/networkservice/common/authorize/server_test.go, pkg/tools/opa/tokens_chain_policy_test.go
This constructor may be useful for forwarder, nsmgr, nse applications
=> Add authn options

pkg/networkservice/utils/inject/injectpeer/client.go
=> Fix inject peer hang

pkg/networkservice/core/next/client.go, pkg/networkservice/core/next/server.go
=> Fix Data race in next.

pkg/networkservice/common/localbypass/server_test.go, pkg/registry/common/localbypass/server.go, pkg/registry/common/seturl/context.go, pkg/registry/common/seturl/server.go
seturl and localbypass should work together.
=> seturl and localbypass should work together.

pkg/networkservice/common/connect/server_test.go, pkg/tools/grpcutils/url.go
=> Fix Host in URLs

pkg/networkservice/common/discover/server.go
Fix Discovery use proper network service
=> Fix Discovery use proper network service

pkg/tools/grpcutils/url.go
=> Support unix sockets

pkg/registry/core/adapters/ns_registry.go, pkg/registry/core/adapters/nse_registry.go
=> Use more tolerant solution to check error on EOF

pkg/networkservice/common/roundrobin/server.go
Check endpoint and return error
=> Check endpoint and return error

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/common/localbypass/server_test.go, pkg/registry/common/seturl/server.go
=> Fix name for seturl nse registry server

pkg/networkservice/chains/endpoint/server.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/registry/server.go, pkg/tools/grpcutils/health.go
This patch can simplify main.go for https://github.com/networkservicemesh/cmd-registry-memory/pull/3
=> Add registry chain

pkg/networkservice/utils/testnse/testnse.go
TestNSE should allow to pass grpc server options
=> TestNSE should allow to pass grpc server options

.github/workflows/update-cmd-registry-memory.yaml
https://github.com/networkservicemesh/cmd-registry-memory/pull/3 has been merged now we can add cmd-registry-memory to updating list.
=> Add updating for cmd-registry-memory

.github/workflows/update-cmd-nsmgr.yaml
=> Allow to auto update cmd-nsmgr

pkg/networkservice/common/connect/server.go, pkg/networkservice/common/connect/server_test.go
remove connect Dial factory stuff
=> remove connect Dial factory stuff

pkg/networkservice/common/updatepath/updatepath_test.go, pkg/networkservice/core/adapters/client_to_server.go, pkg/networkservice/core/adapters/context.go, pkg/networkservice/core/adapters/done_client.go, pkg/networkservice/core/adapters/done_server.go, pkg/networkservice/core/adapters/server_to_client.go, pkg/networkservice/core/next/context.go, pkg/networkservice/core/next/tail_client.go, pkg/networkservice/core/next/tail_server.go
https://github.com/networkservicemesh/sdk/issues/297
With this patch per each adapter in chain, adapter will be called once(in master version twice)
=> Fix performance for next and adapter chains

.golangci.yml, pkg/registry/common/expire/common.go, pkg/registry/common/expire/commont_test.go, pkg/registry/common/expire/doc.go, pkg/registry/common/expire/ns_server.go, pkg/registry/common/expire/ns_server_test.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/expire/options.go, pkg/registry/common/setid/network_service_registry_server.go, pkg/registry/core/adapters/ns_registry.go, pkg/registry/core/adapters/nse_registry.go, pkg/registry/core/streamchannel/ns_registry_stream_channel.go, pkg/registry/core/streamchannel/nse_registry_stream_channel.go, pkg/registry/memory/common.go, pkg/registry/memory/ns_server.go, pkg/registry/memory/nse_server.go, pkg/registry/memory/options.go
https://github.com/networkservicemesh/sdk/issues/307
=> Implement registry expire chain element

pkg/registry/common/refresh/doc.go, pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/registry/common/refresh/options.go
https://github.com/networkservicemesh/sdk/issues/308
=> Add refresh registry chain element

pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
https://github.com/networkservicemesh/sdk/issues/309
=> Fix TODO comment "handle case where NetworkServiceEndpoint is already set"

pkg/registry/common/dnsresolve/common.go, pkg/registry/common/dnsresolve/common_test.go, pkg/registry/common/dnsresolve/const.go, pkg/registry/common/dnsresolve/context.go, pkg/registry/common/dnsresolve/doc.go, pkg/registry/common/dnsresolve/ns_server.go, pkg/registry/common/dnsresolve/ns_server_test.go, pkg/registry/common/dnsresolve/nse_server.go, pkg/registry/common/dnsresolve/nse_server_test.go, pkg/registry/common/dnsresolve/options.go, pkg/tools/interdomain/doc.go, pkg/tools/interdomain/utils.go
https://github.com/networkservicemesh/sdk/issues/370
=> Interdomain: Add registry dnsresolve chain element

pkg/registry/common/swap/doc.go, pkg/registry/common/swap/ns_server.go, pkg/registry/common/swap/ns_server_test.go, pkg/registry/common/swap/nse_server.go, pkg/registry/common/swap/nse_server_test.go
https://github.com/networkservicemesh/sdk/issues/376
=> Interdomain: add registry swap chain element

pkg/networkservice/common/timeout/server.go
Fix timeout chain element data race
=> Fix timeout chain element data race

pkg/registry/common/clienturl/ns_client.go, pkg/registry/common/clienturl/nse_client.go, pkg/registry/common/connect/ns_server_test.go, pkg/registry/common/connect/nse_server_test.go, pkg/registry/common/proxy/common.go, pkg/registry/common/proxy/common_test.go, pkg/registry/common/proxy/doc.go, pkg/registry/common/proxy/ns_server.go, pkg/registry/common/proxy/ns_server_test.go, pkg/registry/common/proxy/nse_server.go, pkg/registry/common/proxy/nse_server_test.go, pkg/tools/interdomain/utils.go
https://github.com/networkservicemesh/sdk/issues/349
This is the last chain element for `proxy-registry-dns`
=> Add proxy registry chain element

pkg/networkservice/common/heal/client_test.go
- remove Eventualy with a conext and channel wait for 500ms max.
=> Fix TestHealClient_Request

pkg/registry/common/swap/ns_server.go, pkg/registry/common/swap/nse_server.go, pkg/registry/interdomain/common_test.go, pkg/registry/interdomain/interdomain_ns_test.go, pkg/registry/interdomain/interdomain_nse_test.go
This PR covers interdomain registry cases via grpc + mocked DNS.
=> Add registry interdomain unit tests

pkg/networkservice/core/adapters/capturecontext_client.go, pkg/networkservice/core/adapters/capturecontext_server.go, pkg/networkservice/core/adapters/client_test.go, pkg/networkservice/core/adapters/client_to_server.go, pkg/networkservice/core/adapters/context.go, pkg/networkservice/core/adapters/server_test.go, pkg/networkservice/core/adapters/server_to_client.go, pkg/registry/core/adapters/ns_capturecontext_client.go, pkg/registry/core/adapters/ns_capturecontext_server.go, pkg/registry/core/adapters/ns_registry.go, pkg/registry/core/adapters/nse_capturecontext_client.go, pkg/registry/core/adapters/nse_capturecontext_server.go, pkg/registry/core/adapters/nse_registry.go
Signed-off-by: Ekaterina Anufrienko <ekanufrienko@mail.ru>
=> Fixed problem #366 for networkservice/core/adapters. Added tests

pkg/networkservice/common/connect/server_test.go, pkg/networkservice/common/heal/client_test.go, pkg/networkservice/common/refresh/client_test.go
Move skipped test back, they still failing and blocking PRs.
=> Move skipped test back

.github/workflows/update-cmd-registry-proxy-dns.yaml
=> Subscribe cmd-registry-proxy-dns on SDK updates

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/common/excludedprefixes/server.go, pkg/networkservice/common/excludedprefixes/server_test.go, pkg/networkservice/common/excludedprefixes/utils.go, pkg/tools/prefixpool/prefixpool.go, pkg/tools/prefixpool/prefixpool_reader.go, pkg/tools/prefixpool/prefixpool_test.go
PR for issue #360
Migrate excluded_prefixes_service as new chain element from monorepo.
Signed-off-by: Ekaterina Anufrienko <ekanufrienko@mail.ru>
=> Created exclude prefixes chain element for server

pkg/registry/memory/ns_server.go
=> Fix edge case for memory registry chain element around deleting channels

pkg/networkservice/common/mechanisms/server.go, pkg/networkservice/common/mechanisms/server_test.go
https://github.com/networkservicemesh/sdk/issues/407
=> fix: mechanisms server doesn't handle the errors

.github/workflows/update-dependent-repositories-gomod.yaml
=> Add repository name to `update gomod matrix` job steps

pkg/tools/grpcutils/listen_and_serve.go, pkg/tools/grpcutils/listen_and_serve_test.go
=> fix: function grpcutls.ListenAndServe should remove socket if it is presented on a host

pkg/registry/common/swap/ns_server.go, pkg/registry/common/swap/nse_server.go, pkg/registry/interdomain/interdomain_ns_test.go, pkg/registry/interdomain/interdomain_nse_test.go
=> fix: nse/ns registry should find a local entry in case of find resource with local domain

pkg/registry/common/expire/nse_server.go
=> Make registry nse expire chain element more tolerant

pkg/registry/core/chain/ns_registry.go, pkg/registry/core/chain/nse_registry.go, pkg/registry/core/trace/ns_registry.go, pkg/registry/core/trace/nse_registry.go, pkg/registry/interdomain/interdomain_ns_test.go, pkg/registry/interdomain/interdomain_nse_test.go
=> fix: registry trace chain element should be used in chain

pkg/networkservice/common/clienturl/context.go, pkg/networkservice/common/discover/context.go, pkg/networkservice/common/localbypass/server_test.go, pkg/networkservice/common/mechanisms/recvnetns/context.go, pkg/networkservice/common/refresh/client_test.go, pkg/networkservice/core/next/context.go, pkg/networkservice/core/trace/context.go, pkg/registry/common/clienturl/context.go, pkg/registry/core/next/context.go, pkg/registry/core/trace/context.go, pkg/tools/log/context.go
=> Replace context.TODO to panic

pkg/tools/prefixpool/prefixpool.go, pkg/tools/prefixpool/prefixpool_test.go
Signed-off-by: Tigran Manasyan <manasyan_tigran@mail.ru>
=> Added nested subnetworks check in prefixpool releasePrefixes method

pkg/networkservice/common/excludedprefixes/options.go, pkg/networkservice/common/excludedprefixes/server.go, pkg/networkservice/common/excludedprefixes/server_test.go, pkg/networkservice/common/excludedprefixes/utils.go
=> Filewatcher of excluded prefixes server now monitors folder

pkg/networkservice/common/interpose/server.go
=> fix: Interpose chain element wrong compares  urls

pkg/networkservice/common/interpose/server.go
Fix issue when interpose chain element doesn't request forwarder on double request
=> Interpose should request forwarder on rerequest

pkg/networkservice/common/macaddr/rand_mac.go, pkg/networkservice/common/macaddr/server.go, pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/const.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/memif/client.go
1. Add macaddr server chain element
2. Add kernel, memif client chain elements
=> Sriov common chains

pkg/networkservice/common/heal/client.go, pkg/networkservice/common/timeout/server.go, pkg/registry/memory/ns_server.go, pkg/registry/memory/nse_server.go
This PR fixes race conditions found by interdomain unit testing. These fixes covered by this PR: https://github.com/networkservicemesh/sdk/pull/465
=> Fix race conditions

go.mod, go.sum, pkg/tools/spire/start.go
Spire agent fails to start in 10 attempts, need to add extra tumeout.
=> Increase spire-agent healthcheck wait time

go.mod, go.sum, pkg/tools/spire/start.go
This reverts commit 0fe42a578069e8c499be33cac1b4eed49debecf0.
https://github.com/networkservicemesh/sdk/pull/481
Is breaking downstream:
https://github.com/networkservicemesh/cmd-forwarder-vppagent/pull/156/checks?check_run_id=1179132829
=> Revert "Increase spire-agent healthcheck wait time (#481)"

pkg/networkservice/common/swap/server.go, pkg/networkservice/common/swap/server_test.go
Part of splitting PR https://github.com/networkservicemesh/sdk/pull/465
=> feat: Add nsmgr-proxy swap chain element

pkg/networkservice/common/interdomainurl/server.go, pkg/networkservice/common/interdomainurl/server_test.go
Part of splitting PR https://github.com/networkservicemesh/sdk/pull/465
=> feat: Add nsmgr-proxy interdomainurl chain element

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/networkservice/common/connect/client.go, pkg/registry/common/querycache/nse_client.go, pkg/registry/common/querycache/nse_client_test.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
https://github.com/networkservicemesh/sdk/pull/465
This PR is the last part of implementing interdomain in SDK.
This PR fixes some small issues that have been found during testing + adds nsmgr-proxy chain.
=> Add nsmgr-proxy into chains

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go
=> Simplify registry refresh chain element

pkg/networkservice/core/next/client.go, pkg/networkservice/core/next/server.go, pkg/networkservice/core/next/tests/client_test.go, pkg/networkservice/core/next/tests/server_test.go, pkg/registry/core/next/ns_registry_server_test.go, pkg/registry/core/next/nse_registry_server_test.go
=> fix: zero size chain should not panic

pkg/networkservice/common/connect/server_test.go
=> Fix connect server tests

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml, go.mod, go.sum
=> Update SDK to go 1.15

pkg/networkservice/common/externalips/server_test.go, pkg/tools/fs/utils.go
https://github.com/networkservicemesh/sdk/issues/532
=> fix: TestExternalIPsServer_NoFile is not stable

pkg/networkservice/common/externalips/server.go, pkg/networkservice/common/externalips/server_test.go
During integration testing, I found that nsmgr-proxy receives only one update from the file.
This PR fixes the issue and adds coverage for this scenario.
=> fix: nsmgr-proxy receives only one update of changing external ips

pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/refresh/client_test.go
``` go
// Create refreshRequest
refreshRequest := request.Clone()
request.Connection = rv.Clone() <-- bug
```
``` go
// Create refreshRequest
refreshRequest := request.Clone()
refreshRequest.Connection = rv.Clone()
```
=> Fix refresh client

pkg/networkservice/chains/endpoint/server.go
Signed-off-by: Tigran Manasyan <tigran.manasyan@xored.com>
=> Revert adding opentracing grpc options to endpoint server

go.mod, go.sum
=> Bump serialize/executor to v1.0.2

.github/workflows/update-dependent-repositories-gomod.yaml
=> subscribe cmd-nsmgr-proxy on updates from sdk

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/interpose/server.go, pkg/networkservice/common/interpose/server_test.go, pkg/registry/common/setid/network_service_registry_server.go, pkg/tools/sandbox/builder.go
=> Pass-through test

pkg/tools/spanhelper/span_helper.go
spanhelper should reuse fields passed to context with log.WithField*()
=> spanhelper should reuse fields passed to context with log.WithField*()

pkg/registry/common/recvfd/server.go
Recvfd Registry should expect Endpoint name on return
=> Recvfd Registry should expect Endpoint name on return

pkg/networkservice/chains/nsmgr/fd_chains.go, pkg/networkservice/chains/nsmgr/fd_chains_linux.go, pkg/networkservice/chains/nsmgr/server.go
NSmgr should send FD to endpoint.
=> NSmgr should send FD to endpoint.

pkg/networkservice/common/filtermechanisms/README.md, pkg/networkservice/common/filtermechanisms/const.go, pkg/networkservice/common/filtermechanisms/options.go, pkg/networkservice/common/filtermechanisms/server.go, pkg/networkservice/common/filtermechanisms/server_test.go
https://github.com/networkservicemesh/sdk/issues/573
=> fix: Filter mechanism chain element works incorrectly in remote case

go.mod, go.sum
Version of grpc was updated to 1.33.2
=> Update version of grpc

.github/workflows/pr-for-updates.yaml
=> Bump: update vsoch/pull-request-action to v1.0.12

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
This PR fixes https://github.com/networkservicemesh/sdk/issues/593
=> fix: Discovery chain element should try to wait NS and NSE on request 

pkg/networkservice/chains/nsmgr/server_test.go
https://github.com/networkservicemesh/sdk/issues/619
=> Disable TestNSMGR_RemoteUsecase_BusyEndpoints

.github/workflows/ci.yaml, .golangci.yml
=> Bump golangci linter to v1.34.0

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
`cmd-vfio-nse` should be updated on `sdk` updates.
=> Add cmd-vfio-nse to dependent repositories

.github/workflows/ci.yaml
=> fix: golangci check fails on the master branch

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> ci: Add sdk-k8s into dependent repositories

pkg/networkservice/ipam/point2pointipam/README.md, pkg/networkservice/ipam/point2pointipam/ip_pool.go, pkg/networkservice/ipam/point2pointipam/meta_data.go, pkg/networkservice/ipam/point2pointipam/server.go, pkg/networkservice/ipam/point2pointipam/server_test.go, pkg/networkservice/ipam/point2pointipam/tools.go
Closes https://github.com/networkservicemesh/sdk/issues/507, https://github.com/networkservicemesh/sdk/issues/639.
=> Rework IPAM

pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go
Registry expire chain element doesn't updates expiration time for the returned endpoint.
Fix it.
=> Fix registry expire

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> Remove sdk-vppagent from dependent repositories

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/clienturl/client.go
Closes https://github.com/networkservicemesh/deployments-k8s/pull/102
=> fix: connectClient freezes on request to dead server

pkg/registry/chains/client/client.go, pkg/registry/common/sendfd/client_linux.go, pkg/registry/common/sendfd/client_other.go
=> feat: add default registry client chains

pkg/networkservice/core/trace/context.go, pkg/registry/core/trace/context.go, pkg/tools/grpcutils/trace.go
=> Enable tracing using grpc metadata

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go
`refresh` uses for `nse.ExpirationTime` first timeout received from the subsequent chain. In case of remote memory registry we have such chain:
```
-- endpoint --
refresh(default_timeout)
...
-- NSMgr --
expire(timeout_1)
...
-- registry --
expire(timeout_2)
...
memory
```
Most probably `timeout_1 << timeout_2 << default_timeout`, because endpoint is on the same node with the NSMgr, but registry is somewhere else.
In such case we got following `nse.ExpirationTime` over time:
```
-- register --
refresh   -> now + default_timeout
expire(1) -> ...
expire(2) -> ...
expire(2) <- now + timeout_2 [starts timer on this time]
expire(1) <- now + timeout_1 [starts timer on this time]
refresh   <- now + timeout_1 [starts timer on this time]
-- refresh register --
refresh   -> now + timeout_1 …
```
=> Fix refresh setting invalid expiration time

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/clienturl/client.go, pkg/networkservice/common/connect/server.go, pkg/networkservice/common/updatepath/common_test.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/utils.go
Depends on https://github.com/networkservicemesh/sdk/pull/716
=> refactor: Use Option pattern in chains/client

pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/authorize/client.go, pkg/networkservice/common/authorize/common.go, pkg/networkservice/common/authorize/options.go, pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_test.go, pkg/tools/opa/all_tokens_valid_policy.go, pkg/tools/opa/last_token_signed_policy.go, pkg/tools/opa/policy.go, pkg/tools/opa/tokens_chain_policy.go, pkg/tools/opa/tokens_expired_policy.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/types.go
Depends on
1. https://github.com/networkservicemesh/sdk/pull/716
2. https://github.com/networkservicemesh/sdk/pull/718
Closes https://github.com/networkservicemesh/networkservicemesh/issues/2138
=> feat: Enable OPA policies by default for NSM applications

pkg/networkservice/common/mechanisms/kernel/client.go
=> fix: mechanisms/kernel do not modify netnsurl if it is presented in parameters

pkg/networkservice/common/mechanisms/client.go, pkg/networkservice/common/mechanisms/client_test.go
=> fix: do not set mechanism in mechanismsClient

pkg/networkservice/common/discover/const.go, pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
=> Add delay before next discover attempt

pkg/networkservice/chains/endpoint/server.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/tools/sandbox/node.go
Refactor `chains/endpoint` to use Option pattern.
Closes #737.
=> Refactor chains/endpoint to use Option pattern 

pkg/networkservice/common/refresh/client.go
Fixes issue with `refresh` and `serialize` merge.
=> Fix networkservice refresh serialize merge issue

pkg/networkservice/common/refresh/client_test.go
=> Skip TestRefreshClient_Stress

pkg/networkservice/common/refresh/client_test.go, pkg/networkservice/common/refresh/client_utils_test.go
Fixes #774
Signed-off-by: Artem Belov <artem.belov@xored.com>
=> Networkservice Refresh tests rework

pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
Fixes #788 
Signed-off-by: Artem Belov <artem.belov@xored.com>
=> Assign Payload to the connection

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/server_test.go, pkg/tools/grpcutils/url.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
Fixes #733 
Refactor chains/nsmgr to use Option pattern
=> Refactor chains/nsmgr to use Option pattern

pkg/networkservice/chains/nsmgr/server_heal_test.go, pkg/networkservice/common/heal/server.go
`Close` doesn't stop healing.
Use context created for healing instead of `f.ctx` in healing.
=> Fix issue with heal close

pkg/networkservice/ipam/point2pointipam/server.go, pkg/networkservice/ipam/point2pointipam/server_test.go
`ipam` chain element doesn't free newly selected IP addresses if next server returns an error.
If IP addresses have been selected in this `Request` and next server returns an error we should free them.
=> Fix ipam next error

.github/workflows/update-dependent-repositories-gomod.yaml
=> fix: condition for update deps job is wrong

pkg/networkservice/chains/nsmgr/nsmgr_test.go
=> Use suites for nsmgr tests

.github/ISSUE_TEMPLATE.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/question.md, .github/ISSUE_TEMPLATE/spec.md
https://github.com/networkservicemesh/sdk/issues/807
=> issue #807 Issue templates

pkg/networkservice/chains/nsmgr/server_heal_test.go
https://github.com/networkservicemesh/sdk/issues/840
=> Skip heal restore tests

pkg/networkservice/chains/nsmgr/server_heal_test.go
https://github.com/networkservicemesh/sdk/issues/845
=> Disable Forwarder heal tests

pkg/tools/fs/utils_test.go
https://github.com/networkservicemesh/sdk/issues/848
=> Disable Test_WatchFile

pkg/registry/common/connect/ns_server.go, pkg/registry/common/connect/nse_server.go, pkg/registry/common/expire/ns_server.go, pkg/registry/common/expire/ns_server_test.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/memory/nse_server.go, pkg/registry/common/querycache/cache.go, pkg/registry/common/querycache/nse_client_test.go, pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/tools/clockmock/mock.go
=> Rework pkg/registry to use clock.Clock

pkg/networkservice/core/adapters/monitor_server_to_client.go
fixes https://github.com/networkservicemesh/sdk/issues/858
=> Fix unstable TestHealClient_Request

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/nsmgr/nsmgr_single_test.go, pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go, pkg/networkservice/connectioncontext/dnscontext/options.go, pkg/networkservice/connectioncontext/dnscontext/server.go, pkg/networkservice/connectioncontext/dnscontext/server_test.go, pkg/tools/dnscontext/config_decoder.go, pkg/tools/dnscontext/config_decoder_test.go, pkg/tools/dnscontext/manager.go, pkg/tools/dnscontext/manager_test.go, pkg/tools/sandbox/node.go
Closes https://github.com/networkservicemesh/sdk/issues/825
Closes https://github.com/networkservicemesh/sdk/issues/836
=> feat: End to end DNS integration: Update dnscontext/client and dnscontext/server to latest changes of SDK 

pkg/networkservice/common/heal/server.go
Fixes https://github.com/networkservicemesh/sdk/issues/857
=> Fix data race in heal server

pkg/networkservice/chains/nsmgr/nsmgr_test.go
=> Fix data race in NSMgr tests

pkg/tools/log/spanlogger/spanlogger.go
Issue #870.
If some chain element has postponed action for `Request`/`Close` that uses log from context, there can be a data race with `.finish()`.
=> Fix data race in spanlogger

pkg/tools/log/defaultlogger.go, pkg/tools/log/emptylogger.go, pkg/tools/log/logger.go
=> Add defaultLogger and use it by default

go.mod, pkg/networkservice/common/connect/client.go, pkg/networkservice/common/connect/server.go, pkg/networkservice/common/connect/server_cancel_test.go, pkg/networkservice/common/discover/server.go
fixes https://github.com/networkservicemesh/sdk/issues/808
=> Fix check for canceled grpc conn in connectServer

pkg/networkservice/common/connect/server_cancel_test.go
=> Fix TestConnect_CancelDuringRequest

.golangci.yml, pkg/tools/matchutils/utils_test.go
leftovers of cancelled https://github.com/networkservicemesh/sdk/issues/871 task
=> Add unit tests for matchutils package

pkg/networkservice/connectioncontext/dnscontext/client_test.go
Closes https://github.com/networkservicemesh/sdk/issues/891
=> fix: Test_DNSContextClient_Usecases is unstable 

.github/PULL_REQUEST_TEMPLATE.md
Closes https://github.com/networkservicemesh/sdk/issues/833
=> feat: Add PR Template

pkg/networkservice/chains/nsmgr/heal_test.go
Closes #845.
Closes #840.
1. 1 second timeout sometimes is not enough to perform a Request, so it should be increased.
2. For restore tests token shouldn't expire because we expect hop to be restored.
=> Fix timeouts in heal tests

.github/workflows/ci.yaml, pkg/tools/fs/utils.go, pkg/tools/fs/utils_test.go
fixes https://github.com/networkservicemesh/sdk/issues/848
=> Fix Test_WatchFile instability

pkg/networkservice/common/mechanisms/recvfd/common.go
=> Add nil check in recvfd

pkg/networkservice/common/mechanisms/vxlan/vni/client.go, pkg/networkservice/common/mechanisms/vxlan/vni/constants.go, pkg/networkservice/common/mechanisms/vxlan/vni/server.go
=> Adapt VNI to use Src/Dst port.

pkg/networkservice/common/refresh/client_test.go
=> [sdk#839] Skip TestRefreshClient_Sandbox

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/client/client_heal_test.go, pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/common/authorize/client.go, pkg/networkservice/common/connect/client.go, pkg/networkservice/common/connect/server.go, pkg/networkservice/common/connect/server_cancel_test.go, pkg/tools/sandbox/node.go
fixes https://github.com/networkservicemesh/sdk/issues/938
=> Add heal elements into client chain

pkg/networkservice/common/updatepath/common.go
=> Fix updatepath to not panic on nil Connection

.github/workflows/ci.yaml, .github/workflows/release.yaml
https://github.com/networkservicemesh/release/issues/1
=> feat: Add release github actions

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/option.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/kernel/utils.go
Add `WithInterfaceName` option to `kernelMechanismServer`
=> Add WithInterfaceName option to kernelMechanismServer

.github/workflows/automerge.yaml, .github/workflows/pr-for-updates.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
First step to make NSMBot messages more human-readable
https://github.com/networkservicemesh/cmd-template/issues/64
=> Formatting change for NSMBot PR message

.github/workflows/update-dependent-repositories-gomod.yaml
https://github.com/networkservicemesh/cmd-template/issues/64
=> qfix: Changed sha retrieving

pkg/networkservice/chains/nsmgr/suite_test.go
Starts refresh request in `Test_ConnectToDeadNSEUsecase` with a new context.
=> [qfix] Fix Test_ConnectToDeadNSEUsecase

pkg/networkservice/common/connect/server_test.go
Some of these checks were accidentally removed during the #806, some of them were just missed.
=> [qfix] Fix goleak checks in connect tests

go.mod, go.sum
Updates used `grpcfd` version.
https://github.com/networkservicemesh/cmd-nsmgr/issues/375
=> Manually update used grpcfd version

.github/workflows/update-dependent-repositories-gomod.yaml
=> Add cmd-admission-webhook-k8s to dependent repos

pkg/networkservice/common/discoverforwarder/server.go
=> [qfix] Fix storing forwarder name

.golangci.yml, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/chains/nsmgr/unix_test.go, pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discoverforwarder/server.go, pkg/registry/common/heal/find_test.go, pkg/tools/sandbox/utils.go
Requires for https://github.com/networkservicemesh/sdk/issues/1094
Requires for https://github.com/networkservicemesh/integration-k8s-kind/pull/454
=> feat: Update discoverforwarder to latest api changes

pkg/networkservice/common/dial/client.go
Fixes https://github.com/networkservicemesh/sdk/files/7519966/nsmgr-phjrv-previous.txt
If dial fails we need to delete `dialer` from metadata
=> [qfix] Delete from clientconn map if dial fails

pkg/registry/chains/memory/server.go, pkg/registry/common/setregistrationtime/doc.go, pkg/registry/common/setregistrationtime/nse_server.go, pkg/registry/common/setregistrationtime/nse_server_test.go
https://github.com/networkservicemesh/sdk/issues/1140
=> Add registration time chain element

.github/workflows/release.yaml
=> Add cmd-admission-webhook-k8s to release workflow

pkg/tools/log/grouplogger.go, pkg/tools/log/logger.go
Needed for https://github.com/networkservicemesh/cmd-nsmgr/pull/422
=> Made group logger creation public

pkg/networkservice/common/mechanisms/vxlan/vni/client.go, pkg/networkservice/common/mechanisms/vxlan/vni/server.go
Added more logs for tracking undesired behaviour
=> Added more logging for vni chain elements

pkg/networkservice/utils/metadata/client.go, pkg/networkservice/utils/metadata/server.go
=> Added logs to metadata

pkg/registry/common/heal/find_test.go, pkg/registry/common/memory/nse_server.go
This PR allows monitoring remote registry.
Discussion here: https://github.com/networkservicemesh/sdk/issues/1170#issuecomment-977168813
https://github.com/networkservicemesh/integration-k8s-kind/issues/460
https://github.com/networkservicemesh/sdk/issues/1170
=> Fix memoryNSE Find

.github/workflows/ci.yaml, pkg/networkservice/common/timeout/server_test.go
https://github.com/networkservicemesh/sdk/issues/939
=> TestTimeoutServer_Request is unstable

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go
Add registration time for `registry` `refresh`
=> [qfix] Add registration time for refresh

.github/workflows/update-dependent-repositories-gomod.yaml
new repository networkservicemesh/cmd-nse-remote-vlan
The new repository depends on sdk
networkservicemesh/cmd-forwarder-vpp#429
- [ X] Have not tested
- [ X] CI
=> Add new depending repository (networkservicemesh/cmd-nse-remote-vlan)

.github/workflows/release.yaml
Signed-off-by: Laszlo Kiraly <laszlo.kiraly@est.tech>
cmd-nse-remote-vlan repository was included in CI pipeline for release.
networkservicemesh/sdk#1222
=> Add nse-remote-vlan to the repo pipeline for release #1222

go.mod, go.sum
=> bump: update grcpfd to latest version

pkg/registry/common/retry/nse_client.go
=> [qfix] Fix registry retry error value

pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go, pkg/networkservice/common/excludedprefixes/client.go, pkg/networkservice/common/excludedprefixes/options.go, pkg/tools/awarenessgroups/config_decoder.go, pkg/tools/awarenessgroups/config_decoder_test.go
https://github.com/networkservicemesh/api/issues/121
=> Mutually Aware NSEs

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> qfix: subscribe new apps on updates from sdk

.github/workflows/ci.yaml, pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/chains/nsmgr/unix_test.go, pkg/tools/sandbox/node.go
Closes https://github.com/networkservicemesh/sdk/issues/1248
=> fix Test_ForwarderShouldBeSelectedCorrectlyOnNSMgrRestart

pkg/registry/common/dial/nse_client.go
=> [qfix] Add default dial timeout for dialNSEClient

pkg/networkservice/common/excludedprefixes/client.go, pkg/networkservice/connectioncontext/ipcontext/vl3/client_test.go
=> qfix: nsc can't refresh connection in interdomain scenarios

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml, .golangci.yml, go.mod, pkg/networkservice/common/excludedprefixes/server_test.go, pkg/networkservice/common/mechanisms/recvfd/server_test.go, pkg/tools/spire/start.go
Closes https://github.com/networkservicemesh/sdk/pull/1266
=> bump: update go to v1.18.1

pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/eventloop.go, pkg/networkservice/common/heal/options.go
=> [qfix] Fix deadlineCtx in eventloop

pkg/registry/common/heal/ns_client.go, pkg/registry/common/heal/nse_client.go
=> [qfix] Use cloned request in heal registry

pkg/tools/sandbox/types.go
=> TestNSMGR_HealRegistry is unstable

pkg/networkservice/connectioncontext/ipcontext/vl3/client.go, pkg/networkservice/connectioncontext/ipcontext/vl3/server.go
**_Tested only with this test on GKE_** - https://github.com/networkservicemesh/deployments-k8s/tree/main/examples/features/vl3-basic
Would like to find out, why this functionality is not working - https://github.com/networkservicemesh/sdk-kernel/blob/main/pkg/kernel/networkservice/connectioncontextkernel/ipcontext/routes/common.go#L64
=> [WIP] Vl3 next-hop fix

.github/workflows/ci.yaml, .github/workflows/release.yaml
https://github.com/networkservicemesh/.github/issues/4
=> Improve release workflow

pkg/registry/common/heal/find_test.go
https://github.com/networkservicemesh/sdk/issues/1157
=> Fix TestHealClient_FindTest

pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/swapip/client.go, pkg/networkservice/common/swapip/client_test.go, pkg/networkservice/utils/checks/checkresponse/client.go
Split swapIP into client and server chain elements
Issue: https://github.com/networkservicemesh/cmd-nsc-simple-docker/issues/1
=> Split swapIP into client and server

.github/workflows/update-dependent-repositories-gomod.yaml
=> Add cmd-cluster-info-k8s repo to dependency list

pkg/networkservice/connectioncontext/dnscontext/client.go
We cannot use metadata this way, because, if the connection is down (healing case) we first call Close, which will remove the metadata, and then re-Request. And in the new Request, we will add the `resolvconfDNSConfig` again (because there is nothing in the metadata)
https://github.com/networkservicemesh/deployments-k8s/issues/7055
=> Remove metadata from dnsContextClient

pkg/tools/dnsutils/fanout/handler.go
https://github.com/networkservicemesh/integration-k8s-kind/pull/715
=> fanout: allow empty answer

pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
=> Revert SupplyRegistryFunc signature in sandbox.Builder

pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go, pkg/networkservice/connectioncontext/dnscontext/resolvconf.go, pkg/networkservice/connectioncontext/dnscontext/resolvconf_test.go
https://github.com/networkservicemesh/sdk/issues/1339
=> DNS: dnscontext doesn't restore resolv.conf

.github/workflows/automerge.yaml
=> Add token to automerge workflow input

pkg/registry/common/grpcmetadata/path.go
=> [qfix] add `json:"token"` tag for PathSegment.Token

pkg/registry/common/authorize/common.go
=> [qfix] Add return statement in getSpiffeIDFromPath func

pkg/registry/common/authorize/common.go, pkg/registry/common/authorize/ns_server.go, pkg/registry/common/authorize/nse_server.go
=> [qfix] Fix empty path panic in Registry Authorize chain elements

.github/workflows/ci.yaml
It will be useful for reviewing huge PRs.
https://github.com/networkservicemesh/sdk/issues/142
=> feat: add code coverage job

.github/workflows/ci.yaml
https://github.com/networkservicemesh/sdk/actions/runs/3870235535
=> qfix: code-cov matrix strategy is incorrect

.github/workflows/release.yaml
=> Fix quotes

pkg/tools/dnsutils/memory/handler.go, pkg/tools/dnsutils/memory/handler_test.go
This PR allows us to process PTR requests
https://github.com/networkservicemesh/sdk/issues/1425
=> [dns]: handle PTR type

.github/workflows/release.yaml
=> qfix: add cluster info k8s to release workflow

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
https://github.com/networkservicemesh/deployments-k8s/issues/9218
=> Add cmd-csi-driver to dependent repositories

.github/workflows/release.yaml
=> [qfix] Remove duplicate cmd-cluster-info-k8s repository

pkg/networkservice/chains/nsmgr/reselect_test.go, pkg/networkservice/chains/nsmgr/unix_test.go, pkg/networkservice/common/begin/server.go, pkg/networkservice/utils/inject/injecterror/error_supplier.go, pkg/registry/utils/inject/injecterror/error_supplier.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/options.go
https://github.com/networkservicemesh/sdk/issues/1454
=> Close with eventFactory from begin.Server in case of RESELECT_REQUESTED

pkg/networkservice/chains/nsmgr/select_forwarder_test.go, pkg/networkservice/common/begin/server.go
=> begin: use the eventFactory context to close eventFactory connection

pkg/networkservice/chains/nsmgr/select_forwarder_test.go
=> qfix: stabilze unstable discover forwarder test

pkg/networkservice/common/monitor/filter.go
Typo from - https://github.com/networkservicemesh/sdk/pull/1413
=> [qfix]: Fix monitorFilter

pkg/registry/common/begin/nse_event_factory.go, pkg/registry/common/begin/options.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/tools/extend/extended.go
https://github.com/networkservicemesh/sdk-k8s/issues/456
=> Extend expireContext in `expire` chain element with values from request context

go.mod, go.sum
Fix problem with linux constant: https://github.com/golang/go/issues/63969
Update `golang.org/x/sys` `v0.14.0` to `golang.org/x/sys` `v0.14.1-0.20231113162313-11eadc05e9bf`
Task: https://github.com/networkservicemesh/sdk/issues/1551
=> Broken "golang.org/x/sys" v0.14.0 dependency

pkg/networkservice/chains/nsmgr/dns_test.go
Unstable test
https://github.com/networkservicemesh/sdk/issues/1537
=> Task:1537 Test_DNSUsecase is unstable

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/select_forwarder_test.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/common/discoverforwarder/server.go, pkg/networkservice/common/heal/client.go, pkg/networkservice/common/monitor/server.go
=> Fix heal after failed refresh

pkg/networkservice/common/mechanisms/common.go, pkg/networkservice/common/mechanisms/server.go
ci is red for the main branch https://github.com/networkservicemesh/sdk/actions/runs/7554933759
=> fix goheader issues in the main branch

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> Add dashboard backend to dependent repositories.

.github/workflows/release.yaml
https://github.com/networkservicemesh/.github/issues/67
=> [qfix] Cleanup release workflow

pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_test.go, pkg/registry/common/authorize/ns_server.go, pkg/registry/common/authorize/ns_server_test.go, pkg/registry/common/authorize/nse_server.go, pkg/registry/common/authorize/nse_server_test.go
Manage values in sync maps a bit better in case of errors
https://github.com/networkservicemesh/sdk/issues/1621
=> Fix some leaks in authorize chain elements

go.mod, go.sum
Related to https://github.com/networkservicemesh/cmd-nsmgr/issues/675 and https://github.com/edwarnicke/grpcfd/issues/25
=> Update grpcfd to latest

pkg/registry/common/recvfd/server.go, pkg/registry/common/recvfd/server_test.go
https://github.com/networkservicemesh/cmd-nsmgr/issues/689
Closes https://github.com/networkservicemesh/cmd-nsmgr/issues/689
=> fix 'Segmentation violation in nsmgr'

pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_test.go, pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/mechanisms/recvfd/server_test.go, pkg/networkservice/utils/checks/checkcontextonreturn/server.go
This reverts commit bf440a38808cb29857b60611d00c43401d473d50.
=> Revert "Revert authorize changes (#1645)"

pkg/tools/log/logruslogger/levelchange.go
Add log level change to trace and back implementation to sdk.
https://github.com/networkservicemesh/deployments-k8s/issues/12296
=> Add log level change based on signals

pkg/networkservice/common/discoverforwarder/server.go
Just a small typo fixed in the log which could be seen for users.
I created this PR directly.
=> Typo fixed in a log.

.golangci.yml, pkg/tools/tracing/grpcoptions.go
https://github.com/networkservicemesh/sdk/issues/1691
=> Remove deprecated opentelemetry interceptors

pkg/tools/prometheus/server.go
Add option to start http server without TLS.
issue: #1652
=> Expose prometheus metrics in http also
