pkg/networkservice/common/authorize/server_test.go, pkg/networkservice/core/next/client.go, pkg/networkservice/core/next/server.go, pkg/networkservice/core/next/server_test.go
NPE:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x9817b7]
goroutine 50 [running]:
testing.tRunner.func1(0xc00022c100)
/usr/local/go/src/testing/testing.go:874 +0x3a3
panic(0xa1eba0, 0x1002630)
/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/networkservicemesh/sdk-vppagent/pkg/networkservice/connectioncontextkernel/ethernetcontext/macaddress.(*setVppMacServer).Request(0x10349d8, 0xbc1900, 0xc00014e7b0, 0xc0001f27c0, 0xa24460, 0x10349d8, 0xbc1900)
/home/user/go/src/github.com/networkservicemesh/sdk-vppagent/pkg/networkservice/connectioncontextkernel …
```
=> Fix npe and add tests to cover for core/next pkg

.github/workflows/update-sdk-kernel.yaml, .github/workflows/update-sdk-vppagent.yaml
Now that we have update/* branches coming in, need to limit downstream branch to things coming in on master
=> Fix so we only push downstream on changes to master branch

.github/workflows/ci.yaml, .github/workflows/update-sdk-kernel.yaml, .github/workflows/update-sdk-vppagent.yaml
This is because it looks like go 1.13 doesn't properly
handle
go get -u
when updating modules (should also update dependencies)
where as go 1.13.4 (tested locally) does.
=> Change from go version 1.13 -> 1.13.4

.github/workflows/update-sdk-kernel.yaml, .github/workflows/update-sdk-vppagent.yaml
Turns out that sometimes the google go module proxy isn't
quick about getting updated from github.com. Since obviously
we want to get this right, we use GOPROXY=direct to force
it to go to the direct source.
=> Use GOPROXY=direct for update-*.yaml

pkg/networkservice/common/connect/server.go
It could help to write tests that depend on `connect` package. 
For example to testing `directmemif` package.
=> Add client dial options to `connectServer`

.github/workflows/ci.yaml, .github/workflows/nsmbot-automerge.yaml
If and only if:
- Checks pass
- They only change go.sum or go.mod
- They do not introduce any new 'replace' directives into go.mod.
=> Automerge nsmbot update PRs

pkg/networkservice/core/eventchannel/monitor_client.go, pkg/networkservice/core/eventchannel/monitor_client_test.go, pkg/networkservice/core/eventchannel/monitor_connection_client.go, pkg/networkservice/core/eventchannel/monitor_connection_client_test.go, pkg/networkservice/core/eventchannel/monitor_connection_server.go, pkg/networkservice/core/eventchannel/monitor_connection_server_test.go, pkg/networkservice/core/eventchannel/monitor_server.go, pkg/networkservice/core/eventchannel/monitor_server_test.go
This provides machinery to allow the creation of various MonitorConnection clients/servers backed
by event channels.  This aids in construction of both adapters and the building of tests.
=> Add eventchannel networkservice chain element

pkg/networkservice/core/next/client.go, pkg/networkservice/core/next/context.go, pkg/networkservice/core/next/server.go, pkg/networkservice/core/next/tail_client.go, pkg/networkservice/core/next/tail_server.go
Right now in the event where you run a chain element outside of a chain, you will get a panic
on calls to things like:
next.Server(ctx).Request(...)
This fixes that.  Now it never panics.
=> Fix next to *always* work.

pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
Added tests for /pkg/networkservice/common/discover package
=> Add discoverServer tests

pkg/networkservice/core/trace/context.go, pkg/tools/spanhelper/span_helper.go
Turns out that logrus.New() pegs us to things like stderr for output.
Since by default for testing we want to use:
logrus.SetOutput(ioutil.Discard)
to suppress logs, its important to take defaults from the global logrus settings.
=> Minor fix to logging to make us take global logrus defaults.

pkg/networkservice/common/mechanisms/server.go
mechanisms.NewServer(map[string]networkservice.NetworkServiceServer) presumes
that the provided implementations for a mechanism *don't* chain, but simply return to it when they are done.
The probability of an implementor getting that right is basically zero, so we wrap them in a chain
to make sure that if they call next.Server(ctx).{Request/Close} they don't continue down the
chain that mechanisms.NewServer is on.
=> Add defensive code in case mechanism elements are mistakenly chain elmements

.golangci.yml, go.mod, go.sum, pkg/tools/security/provider.go, pkg/tools/security/spire.go, pkg/tools/security/test/provider.go, pkg/tools/security/test/utils.go, pkg/tools/security/token.go, pkg/tools/security/token_test.go
Add two functions:
- `GenerateToken(ctx context.Context, p Provider, expiresAt time.Duration) (string, error)`
- `VerifyToken(token string, x509crt *x509.Certificate) error` 
Cover them with unit tests.
Signed-off-by: Ilya Lobkov <ilya.lobkov@xored.com>
=> Add util functions for tokens

pkg/networkservice/common/heal/client_test.go, pkg/networkservice/core/eventchannel/monitor_client.go
**Problem:**
Undefined order of execution between `monitorConnectionClient.eventLoop()` goroutine that passes events to `fanoutEventCh` and goroutine that's waiting `<--context.Done()` and closes `fanoutEventCh` leads to different number of `testOnHeal.Request()` calls in `/pkg/networkservice/common/heal/client_test.go`
`TestNewClient_MissingConnectionsOnInit` test that leads to different number (2 or 3) `testOnHeal.Request()` invocations. [Explanation diagram](https://drive.google.com/file/d/1yDwcyOjTQrcif8B_RvndGDDyxH3qzmN3/view?usp=sharing)
**Solutions i see:**
1) `time.Sleep(100 * time.Millisecond)` after sending `INITIAL_STATE_TRANSFER` event to ensure that this event will be handled earlier than context cancellation.
2) Guarantee that chain context cancellation will be handled after …
=> Fix race condition in MonitorConnectionClient

pkg/networkservice/core/next/client.go, pkg/networkservice/core/next/context.go, pkg/networkservice/core/next/server.go, pkg/networkservice/core/next/tests/client_test.go, pkg/networkservice/core/next/tests/server_test.go
https://github.com/networkservicemesh/sdk/issues/172
=> Add the possible to make chain of chains via pkg/next

pkg/networkservice/common/authorize/server_test.go, pkg/networkservice/common/heal/client.go, pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/timeout/server.go, pkg/networkservice/core/trace/client.go, pkg/networkservice/core/trace/server.go, pkg/networkservice/core/trace/utils.go, pkg/registry/core/trace/discovery_client.go, pkg/registry/core/trace/discovery_server.go, pkg/registry/core/trace/registry_client.go, pkg/registry/core/trace/registry_server.go, pkg/registry/core/trace/utils.go, pkg/tools/typeutils/typeutils.go
Also added package information to types in trace and fixed
places in the code where we were manually wrapping in chain element.
=> Move wrapping of errors for stacktraces into the trace package

pkg/tools/callback/server_test.go
There appear to be race conditions in callback tests that are blocking
other work:
https://github.com/networkservicemesh/sdk/pull/193/checks?check_run_id=583900079
https://github.com/networkservicemesh/sdk/pull/192/checks?check_run_id=583894137
This diables those tests till the issue can be resolved.
=> Disable callback tests till raceconditions can be fixed.

pkg/networkservice/chains/client/client.go, pkg/networkservice/utils/inject/injectpeer/client.go
It  is desirable to know the grpc.Peer information of your server, so for example, you can add
a proper 'aud' claim to a JWT Token.
golang grpc doesn't provide the grpc.Peer information to clients unless
(1)  They ask for it with the grpc.Peer grpc.CallOption
(2)  Even then, only on return.
This chain element compensates for that by:
(1)  Adding the grpc.Peer grpc.CallOption to its call to next.Client(ctx)
(2)  Keeping a running record on the return of the grpc.Peer
(3)  Injecting that grpc.Peer into the context used to call next.Client(ctx) once it has a grpc.Peer on record
(4)  If and only if it it doesn't havea grpc.Peer and its call to next.Client(ctx) return an error, tries doing
the call again *with* the grpc.Peer added to the context to see if that clears up the error.
=> Add injectpeer NetworkServiceClient chain element

pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/server.go
It turns out that the most reliable human behavior is to presume
that folks will keep folling the pattern of calling next.Client
or next.Server and so we adapt to simply presuming on that here.
=> Fix to mechanisms to play nice with previous fix to next.

pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/refresh/client_test.go
Handle possible situation when `time.Stop()` doesn't stop already started refresh gotoutine from previous `Request()` or at `Close()` invocation
=> Fix time.Stop() may not stop already started refresh

.golangci.yml, pkg/tools/debug/self.go
Package debug provides a very simple function that, if executed will replace the executable with dlv running the executable and listening on the port specified by an environment variable.
Example:
if err := debug.Self(); err != nil {
fmt.Println(err)
}
If an err is returned, it will provide full explanation for what
must be done to debug.  For example, if you've not set the dlv listen port
env at all, you will get an error:
"Setting env variable DLV_LISTEN_<executable name> to a valid dlv '--listen' value will cause the dlv debugger to execute this binary and listen as directed."
=> debug.Self() - enable all executables to be self debugging

pkg/tools/signal/context.go
Provides a simple 'With' to allow a context to be cancelled
upon receiving an os.Signal.
=> signal.WithSignal(parent context.Context,sigs ...os.Signals) context.Context

.github/workflows/ci.yaml
Turns out... when the automerge job is the reason that a PR is merged
(say an upstream push from nsmbot)... that doesn't trigger the follow
on job in update-sdk-vppagent.yaml and update-sdk-kernel.yaml
So... we add it into the workflow in ci.yaml
=> Fix transitive automerge

pkg/tools/spire/agent.conf.go, pkg/tools/spire/server.conf.go, pkg/tools/spire/start.go
Make spire go tools path independent and do folder cleanup on exit.
=> Make spire go tools path independent

pkg/networkservice/core/eventchannel/monitor_server.go, pkg/networkservice/core/eventchannel/monitor_server_test.go, pkg/networkservice/core/eventchannel/option.go
Fixes unstable test `TestMonitorConnectionServer_MonitorConnections` on CI.
For example, Here is CI build from memory registry elements PR: https://github.com/networkservicemesh/sdk/pull/241/checks?check_run_id=655521550
Based on https://github.com/networkservicemesh/sdk/pull/234
=> Fix concurrency in eventchannel tests

pkg/tools/opautils/opainput.go, pkg/tools/opautils/opainput_test.go
Now OPA input provides the following objects:
1. All information about connection (usage: input.connection.[...]. For example, a token from zero path segment we can get as input.connection.path.path_segments[0].token)
2. The TLSInfo (as retrieved by peer.FromContext for Server or grpc.Peer for the Client) which contains the following data: 
*	"certificate"  --  is  a  pem  encoded  x509cert  (usage:  input.auth_info.certificate)
*	"spiffe_id"  --  is  a  spiffeID  from  SVIDX509Certificate  (usage:  input.auth_info.spiffe_id)
3. "operation"  --  one  of  request/close  (usage:  input.operation)
4. "role"  --  one  of  client/endpoint  (usage:  input.role)
An example of using OPA input for the case of token signature verification
```
package test 
default allow = false    
allow { 
token …
```
=> Prepare input for OPA

pkg/networkservice/common/localbypass/server.go, pkg/networkservice/common/localbypass/server_test.go, pkg/registry/common/localbypass/server.go
Fix localbypass to use endpoint url for identification.
Depenes on:
https://github.com/networkservicemesh/api/pull/40
=> Add endpoint url for identification

pkg/tools/opautils/opainput.go, pkg/tools/opautils/opainput_test.go
=> Remove unused 'role' and 'operation' fields from OPA input

pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/refresh/client_test.go, pkg/networkservice/common/refresh/context.go
Implementation of #237 
Fixed data race between refresh goroutines and close calls/new requests from heal. In some situations there wasn't enough to call `timer.Stop()` to really stop refresh goroutine. I've added context for each refresh and moved timer creation to synced block to fix it. 
Also fixed invalid second request initialization in `TestNewClient_StopRefreshAtAnotherRequest`, that also led to data race. 
Harmless refactoring.
=> Fix data races in RefreshClient

.golangci.yml, pkg/tools/callback/callback.pb.go, pkg/tools/spire/agent.conf.go, pkg/tools/spire/options.go, pkg/tools/spire/start.go
Turns out, spire-agent only polls spire-server
every 5 seconds.  This means that if we run spire-server, then
spire-agent, then add entries... it can take up to six seconds
to get our SVID.
By moving to options, we can:
1.  Start spire-server
2.  Create entries
3.  Start spire-agent
And spire-agent *starts* with the entries and can thus issue ids.
=> Updated spire to handle entries via options

pkg/networkservice/core/trace/client.go, pkg/networkservice/core/trace/server.go, pkg/registry/core/trace/discovery_client.go, pkg/registry/core/trace/discovery_server.go, pkg/registry/core/trace/registry_client.go, pkg/registry/core/trace/registry_server.go, pkg/tools/typeutils/typeutils.go
GetFunc was returning information about the point at which the
interface was defined, not the implementation.  This fixes that.
=> Fix GetFunc

pkg/networkservice/core/trace/context.go, pkg/tools/spanhelper/span_helper.go
Direct usage of logrus.StandardLogger().Hooks may cause cuncurrent map troubles. So make a copy.
=> Fix logrus usage concurrency

pkg/registry/core/next/clients/discovery_client.go, pkg/registry/core/next/clients/nsm_client.go, pkg/registry/core/next/clients/registry_client.go, pkg/registry/core/next/context.go, pkg/registry/core/next/tail_discovery_client.go, pkg/registry/core/next/tail_discovery_server.go, pkg/registry/core/next/tail_nsm_registry_client.go, pkg/registry/core/next/tail_nsm_registry_server.go
+ Network Service Registry adapters, to support next, in case of native(grpc, etc) clients.
* Fix for discovery next
* Tail should not return error.
=> Network Service Registry adapters

.golangci.yml, pkg/networkservice/ipam/point2pointipam/server.go, pkg/networkservice/ipam/point2pointipam/server_test.go
1. Moved tests to separate pkg `point2pointipam_test`
2. Used variadic syntax for point2pointipam.NewServer()
3. Do not use pkg "errors"
4. Added lazy init:
It changed signature from
```go
NewServer(...) (networkservice.NetworkServiceServer, error)
```
to
```go
NewServer(...) networkservice.NetworkServiceServer
```
=> Small fixes for point2pointipam pkg

pkg/registry/core/nextwrap/ns_registry_client.go, pkg/registry/core/nextwrap/ns_registry_client_test.go, pkg/registry/core/nextwrap/nse_registry_client.go, pkg/registry/core/nextwrap/nse_registry_client_test.go
Was missed nextwrap chain elements that used to wrap chain element to support pkg `next`.
=> Add missed nextwrap chain elements

pkg/registry/core/next/ns_registry_client.go, pkg/registry/core/next/ns_registry_server.go, pkg/registry/core/next/ns_registry_server_test.go, pkg/registry/core/next/nse_registry_client.go, pkg/registry/core/next/nse_registry_server.go, pkg/registry/core/next/nse_registry_server_test.go
We've fixed a similar problem in `networkservice/core/next` pkg(https://github.com/networkservicemesh/sdk/pull/310)  but did not fix for registry.
=> Fix data race in registry/core/next pkg

pkg/networkservice/common/refresh/client_test.go
For some reason, currently unstable tests https://github.com/networkservicemesh/sdk/issues/237, https://github.com/networkservicemesh/sdk/issues/260 fail on each osx-test job run.
This PR temporarily disables them.
=> Temporarily disable unstable tests

pkg/registry/core/nextwrap/ns_registry_client.go, pkg/registry/core/nextwrap/ns_registry_client_test.go, pkg/registry/core/nextwrap/nse_registry_client.go, pkg/registry/core/nextwrap/nse_registry_client_test.go
Problem: In master branch nextwrap ignores inner client find stream result. This problem is blocking testing for nsmgr.
And we already have the fix for nextwrap https://github.com/networkservicemesh/sdk/pull/320, but @edwarnicke not sure in this patch because it adds some complexity for the registry chains. 
So we can just use some small temporary fix for this issue at this moment to do not block nsmgr stream.
=> Temporary fix for nextwrap

pkg/registry/core/adapters/ns_registry.go, pkg/registry/core/adapters/nse_registry.go, pkg/registry/core/next/tail_ns_registry.go, pkg/registry/core/next/tail_nse_registry.go, pkg/registry/memory/ns_server.go, pkg/registry/memory/ns_server_test.go, pkg/registry/memory/nse_server.go, pkg/registry/memory/nse_server_test.go
@haiodo has found during nsmgr + registry grpc testing that we should get rid of using io.EOF for our adapters and next stream chain elements because it works wrong with grpc.
=> Do not return io.EOF for tail server registry chain elements

pkg/registry/core/adapters/common_test.go, pkg/registry/core/adapters/ns_registry.go, pkg/registry/core/adapters/ns_registry_test.go, pkg/registry/core/adapters/nse_registry.go, pkg/registry/core/adapters/nse_registry_test.go, pkg/registry/core/streamchannel/ns_registry_stream_channel.go, pkg/registry/core/streamchannel/nse_registry_stream_channel.go
An adapted server should ignore EOF error from the wrapped client
=> Fix: adapted server should ignore io.eof from client

pkg/tools/callback/readme.md, pkg/tools/callback/server.go, pkg/tools/callback/server_test.go
In many places in our code, we need to be able to pass in a simple grpc.DialOption
rather than a function that can be called to return them.  This makes that possible.
=> Introduce simple server.WithCallbackDialer() that does not require arguments

pkg/networkservice/common/connect/server.go
Otherwise, we don't get correct cleanup in xconnects
=> connect.Close() must call client.Close before next.Server(ctx).Close

pkg/registry/common/expire/ns_server_test.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/registry/common/refresh/options.go
https://github.com/networkservicemesh/sdk/issues/308
If refresh client tries to register NSE with expiration_time = nil then it can set some default value.
=> Registry refresh client should be able to set a default expiration time for NSE

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/registry/common/refresh/options.go
During testing in registry-memory found that refresh client chain element is working incorrectly with grpc. It should set expiration_time for nse before call the next client.
=> Fix: refresh client should set expire_time before call the next client

pkg/networkservice/common/connect/server_test.go, pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/client_test.go, pkg/networkservice/core/eventchannel/monitor_client.go
Heal had a few issues:
1.  It was doing an expensive init in the constructor
2.  The eventLoop could be clearer and simpler
3.  There unecessary information being kept at struct{} level
4.  It was attempting to Close things after the clientContext was Done.
This is pretty much guaranteed to fail, as when the clientContext is Done, so typically is
the grpc.ClientConn for the underlying connection.  If we want to handle graceful Close
when shutting down a client, we probably need to do that in a separate chain element.
This is why closers were removed and TestHealClient_MonitorClose was deleted.
=> Rework heal.

pkg/networkservice/common/refresh/client_test.go
https://github.com/networkservicemesh/sdk/issues/237
=> Disable unstable test TestNewClient_StopRefreshAtClose

pkg/networkservice/chains/endpoint/server.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/clienturl/client.go, pkg/networkservice/common/connect/server_test.go, pkg/networkservice/common/heal/client_test.go, pkg/networkservice/common/monitor/server.go, pkg/networkservice/common/monitor/server_test.go, pkg/networkservice/common/refresh/client_test.go, pkg/registry/common/clienturl/ns_client.go, pkg/registry/common/clienturl/ns_client_test.go, pkg/registry/common/clienturl/nse_client.go, pkg/registry/common/clienturl/nse_client_test.go, pkg/registry/common/connect/ns_server.go, pkg/registry/common/connect/ns_server_test.go, pkg/registry/common/connect/nse_server.go, pkg/registry/common/connect/nse_server_test.go, pkg/registry/common/proxy/common_test.go, pkg/registry/common/proxy/ns_server_test.go, pkg/registry/common/proxy/nse_server_test.go, pkg/registry/interdomain/interdomain_ns_test.go, pkg/registry/interdomain/interdomain_nse_test.go
Move from runtime.SetFinalizer to context with proper lifecycle
It seems it fixes all unstable tests, so I've re-enabled them :-)
=> Move from runtime.SetFinalizer to context.Context with proper lifecycle

pkg/networkservice/common/mechanisms/server.go, pkg/networkservice/common/mechanisms/server_test.go
Implementation of #402 
Previously, in the one situation mechanismsServer called `next.Server(ctx).Request/Close` itself, but all of the each mechanism Servers called `next.Server...` too. Now mechanismsServer simply returns `conn` from selected mechanism Server request
=> Fix mechanismsServer next chain element call

.github/workflows/update-dependent-repositories-gomod.yaml
This way the update-dependent-repositories-gomod.yaml file
is portable to new repos, only having to be changed in terms of
Which downstream repos to push to.
=> Switch to pushing to update/${{ github.repository }}

pkg/tools/grpcutils/dial.go, pkg/tools/grpcutils/dial_test.go
When using NSM applications with ListenOn based on `unix` then client application could fail because of k8s is not guarantee that server socket will be immediately provided.
=> Add grpcutils.DialContext function for NSM clients

pkg/tools/grpcutils/listen_and_serve.go
=> fix: grpcutils.ListenAndServe add a check if previous socket file was deleted successfully

pkg/registry/common/dnsresolve/common.go, pkg/registry/common/dnsresolve/ns_server_test.go, pkg/registry/common/dnsresolve/nse_server_test.go, pkg/registry/interdomain/common_test.go
In k8s to search the registry by domain we should include service name into query, example: https://github.com/networkservicemesh/sdk/compare/master...denis-tingajkin:fix_dnsresolve?expand=1#diff-c9d8b841fcd143230a5ca28860c6e096R40
=> fix: dnsresolve chain element should include service name into query

pkg/networkservice/common/excludedprefixes/const.go, pkg/networkservice/common/excludedprefixes/server.go
Constants are needed for networkservicemesh/cmd-exclude-prefixes-k8s#7
=> Excluded prefixes file constants now are exported

pkg/networkservice/core/eventchannel/monitor_client_test.go, pkg/networkservice/core/eventchannel/monitor_connection_client_test.go
Add support for go 1.15 for tests to compile.
=> Add support for go 1.15

pkg/tools/grpcutils/url.go
We should return host not path for unspecified IPs
=> We should return host not path for unspecified IPs

pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
Return error in case no network service is defined
=> Return error in case no network service is defined

.golangci.yml, pkg/networkservice/chains/client/client.go, pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/client_test.go, pkg/networkservice/common/heal/constants_test.go, pkg/networkservice/common/heal/constants_windows_test.go, pkg/networkservice/common/updatetoken/client.go, pkg/networkservice/core/adapters/monitor_server_to_client.go, pkg/networkservice/core/eventchannel/monitor_client.go, pkg/networkservice/core/eventchannel/monitor_connection_client.go, pkg/networkservice/core/eventchannel/monitor_connection_client_test.go
The updatetoken chain element should restore the Connection.Id to match Path.PathSegment[Index].
Additionally, updatetoken should be the last thing that happens before
sending out the RPC call, so as to insure the Connection.Id and Path.Index
are always for the Connection.Id within the client when in client chain
elements.
This is important because otherwise the Connect.Id on the return through the
client does not match the Request.Connection.Id, and various indexing by identifiers
fails to work properly (including things like heal etc).
Because injectpeer is simply present to enable updatetoken, it is also moved
to the end of the chain just before updatetoken.
Unfortunately, this revealed a huge number of race conditions in the heal chain element,
which has been completely reworked to …
=> Rework heal chain element to support updatetoken restoring Connection.Id to the Path.Index

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/heal/client_test.go, pkg/registry/chains/memory/server.go, pkg/registry/common/expire/ns_server.go, pkg/registry/common/expire/ns_server_test.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/memory/ns_server.go, pkg/registry/memory/nse_server.go, pkg/tools/sandbox/README.md, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/doc.go, pkg/tools/sandbox/fake_resolver.go, pkg/tools/sandbox/types.go, pkg/tools/sandbox/utils.go
https://github.com/networkservicemesh/sdk/issues/406
This PR is part of splitting PR https://github.com/networkservicemesh/sdk/pull/465
This part adds using the real registry chains for nsmgr testing.
Also, this PR moves chainstest into pkg `sandbox`.
=> feat: Add nsmgr-proxy chain elements: add pkg/tools/sandbox

pkg/registry/chains/proxydns/server.go, pkg/registry/common/dnsresolve/nse_server.go, pkg/registry/common/proxy/nse_server.go, pkg/registry/common/swap/nse_server.go, pkg/registry/common/swap/nse_server_test.go, pkg/registry/interdomain/interdomain_nse_test.go, pkg/tools/matchutils/utils.go
#406
This PR is part of splitting PR #465
This part fixes a case when the registry find NSE by ns name with "@"
=> fix: interdomain registry chain elements should work correctly on passed interdomain ns

go.mod, go.sum, pkg/tools/spire/start.go
Spire agent fails to start in 10 attempts while testing on packet setup:
```
...
Sep 29 01:56:12.171 [INFO] [cmd:spire-agent healthcheck] Agent is unavailable.
Sep 29 01:56:12.170 [INFO] [cmd:spire-agent run] time="2020-09-29T01:56:12Z" level=warning msg="Current umask 0022 is too permissive; setting umask 0027."
Sep 29 01:56:12.192 [INFO] [cmd:spire-agent healthcheck] Agent is unavailable.
Sep 29 01:56:12.170 [INFO] [cmd:spire-agent run] time="2020-09-29T01:56:12Z" level=warning msg="Insecure bootstrap enabled; skipping server certificate verification" subsystem_name=attestor
Sep 29 01:56:12.214 [INFO] [cmd:spire-agent healthcheck] Agent is unavailable.
Sep 29 01:56:12.230 [INFO] [cmd:spire-agent healthcheck] Agent is unavailable.
Sep 29 01:56:12.253 [INFO] [cmd:spire-agent healthcheck] …
```
=> Add spire healthcheck timeout

pkg/tools/sandbox/builder.go
=> fix: correctly pass generate token func for forwarders in sandbox

pkg/networkservice/common/heal/client_test.go
Skip TestHealClient_Request due to failures: https://github.com/networkservicemesh/sdk/issues/375
=> Skip TestHealClient_Request

.github/workflows/pr-for-updates.yaml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Fix use of deprecated set-env

pkg/tools/spire/server.conf.go
Remove deprecated upstream_bundle spire server option
According to https://github.com/spiffe/spire/pull/1702
=> Remove deprecated upstream_bundle spire server option

pkg/networkservice/common/connect/DESIGN.md, pkg/networkservice/common/connect/client.go
`connectClient` replaces the incoming `Connection` with the previously saved one. (see the [code])
This means that any update to the `Connection.Path` made by `updatetoken` is rolled back, which isn't good since it stucks with stale tokens.
These stale tokens, in turn, make the `refreshClient` insane, because it tries to update them by sending a request, but it won't help, and the refresh interval eventually becomes negative.
[code]: https://github.com/networkservicemesh/sdk/blob/d5972d9e33919cc5d2d88353d9335f0ecc1d4fe6/pkg/networkservice/common/connect/client.go#L50
Let the `connectClient` pass the request as is except `Connection.Mechanism` (stored) and `MechanismPreferences` (set to nil).
<details><summary>(outdated)</summary>
This PR extends the logic of this change made in #502: …
=> connect: Combine connections

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
update-dependent-repositories-gomod fails fast and other repositories don't update (if one of the repositories can not be updated)
=> fix: update-dependent-repositories-gomod fails fast

pkg/networkservice/common/mechanisms/recvfd/client.go
Previous we were allowing the recvfd files to be closed by their
finalizer and the GC.
This sometimes led to premature closing of files leading to errors like:
https://github.com/networkservicemesh/cmd-forwarder-vppagent/issues/187
'Delete' case.  This fixes that by closing the files only after the
ctx has is Done.
=> Explicitely close files for recvfd client *after* they don't matter.

pkg/networkservice/common/interpose/server.go, pkg/registry/common/interpose/server.go
1. Simplify check for direction, if active connections contain path with longest index, we already visited interpose, if not we not.
2. Always generate uniq interpose endpoint name.
=> Fix interpose chain element

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/common/excludedprefixes/server.go
NSMgr stores `inode://` URL in interpose registry and then fails to access forwarder.
```go
newRecvFDEndpointRegistry(), // <-- first replace `inode` URL with `unix` URL
urlsRegistryServer, // <-- then store it into the interpose registry
```
=> Fix issue with storing invalid URL in interpose registry

pkg/networkservice/chains/client/client.go
The issue with the old code (simplified for the clarity):
```go
var rv networkservice.NetworkServiceClient
onHeal = addressof.NetworkServiceClient(rv)
rv = something()
// Now, *onHeal == nil, which isn't expected
```
This code is an equivalent to the following:
```go
var rv networkservice.NetworkServiceClient
client := rv
onHeal = &client
rv = something()
// Now, *onHeal == nil, which isn't expected
```
The new code:
```go
var rv networkservice.NetworkServiceClient
onHeal = &rv
rv = something()
// *onHeal == rv, as expected
```
---
Related: https://github.com/networkservicemesh/sdk/issues/534#issuecomment-709687956
This is not the only instance where a similar issue with `addressof` occurs, I'll address the others in a separate issue.
=> Remove addressof from the client chain

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/discover/server.go
This PR fixes #570 for Local/Remote one-hop NSMgr use-cases.
=> discoverServer: handle Close

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/interpose/server.go
If we have such chain:
```
client -> NSMgr -(1)-> Forwarder -> NSMgr -(2)-> pass through NSE -> NSMgr -(3)-> Forwarder -> NSMgr -(4)-> NSE
```
on (3) interpose chain element should create a new `connectionInfo` for the connection, but there is an existing `connectionInfo` for some Connection.ID from the connection path, so it doesn't do it.
Add `connectionInfo.clientConnID` field and add `connectionInfo` by both client and forwarder connection ID. Check whether the last actual connection ID in the path matches `connectionInfo.clientConnID` or not.
=> Fix issue with interpose chain element in passthrough case

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/common/interpose/server.go, pkg/networkservice/common/interpose/server_test.go
`interpose.NewServer()` works incorrect for refresh, close scenarios. Existing test doesn't cover it.
Remove bool switches, check _if interpose_ case with `connectionInfo.clientConnID`. Add valid test.
=> Fix interpose

pkg/tools/grpcutils/url.go
=> fix: AddressToURL should not return local host in case of IP.IsUnspecified

pkg/networkservice/common/interpose/server_test.go, pkg/networkservice/common/updatepath/client.go, pkg/networkservice/common/updatepath/client_test.go, pkg/networkservice/common/updatepath/common.go, pkg/networkservice/common/updatepath/server.go, pkg/networkservice/common/updatepath/server_test.go, pkg/networkservice/common/updatetoken/client.go, pkg/networkservice/common/updatetoken/client_test.go, pkg/networkservice/common/updatetoken/server_test.go, pkg/tools/opa/tokens_chain_policy_test.go
Update path doesn't update path index back on return. If chain elements accesses `Path.Index` `after next.().Request` there is no guarantee that it is pointing to the current path segment.
Set `conn.Path.Index = request.Connection.Path.Index` on return.
=> Make updatepath restore path index on return

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go, pkg/networkservice/common/roundrobin/server.go
https://github.com/networkservicemesh/sdk/issues/597
=> fix: common/roundrobin: should handle a case if selected endpoint returns error

pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/networkservice/common/interdomainurl/server.go, pkg/networkservice/common/interdomainurl/server_test.go
interdomainURLServer updates `Request.Connection.NetworkServiceEndpointName` from `nse@domain.url` to `nse` and doesn't set it back to the returned `Connection`. If no one before in the chain saves full name, `@domain.url` will be lost and refresh request will be trying to find `nse` locally until timeout.
Set `Connection.NetworkServiceEndpointName = interDomainNSEName` on return.
=> Set back nse@domain name on return from interdomainURLServer

go.mod, pkg/networkservice/common/heal/client_test.go, pkg/networkservice/common/roundrobin/round_robin_selector_test.go, pkg/registry/memory/nse_server_test.go, pkg/tools/matchutils/utils.go
=> Replacing comparison of proto messages

pkg/tools/clientmap/README.md, pkg/tools/clientmap/bench_test.go, pkg/tools/clientmap/refcount.go, pkg/tools/clientmap/refcount_test.go
Existing refcount map is incorrect, such test can fail:
```go
var m clientmap.RefcountMap
m.Store("a", null.NewClient())
var loaded bool
go func() {
_, loaded = m.Load("a") // count += 1 (if exists)
}()
go m.Delete("a") // count -= 1 (delete if 0)
_, exists := m.Load("a")
require.Equal(t, loaded, exists) // if loaded, Delete can't delete, only should decrement the count
```
Rework refcount map with per-entry locks, add action tests, add bench tests.
=> Rework clientmap.RefcountMap, add tests, add bench tests.

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Closes https://github.com/networkservicemesh/sdk/issues/635
=> fix: Add skip updating a dependent repo if the dependent repo already is up to date

.github/workflows/ci.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
=> fix: diff check don't work with unstaged files

pkg/registry/common/expire/ns_server.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/options.go
During testing cmd-registry-k8s were found a few issues:
1. `expire` ns registry chain element uses deadline context
2. `expire` nse registry chain element should use actual NSE on unregistering
=> fix: expire chain element could work incorrectly with registry-k8s

pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/client_test.go, pkg/networkservice/common/heal/constants_test.go
Fixes #375
`TestHealClient_Request` - removed first `MonitorConnections` with the calls context to avoid Server to send commands to almost canceled context.
`TestNewClient_MissingConnectionsInInit` - test removed. Heal client has a check that the expected connection was received and return an error on `Request` otherwise.
=> Stabilize heal tests

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/discover/server.go
Currently, if the endpoint is restarting discover excludes him from the selection list.
=> fix: discover should allow try to select restarting endpoints

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go
If the next of the `refresh` chain element does remote register then `refresh` doesn't set the expiration time for the response.
=> fix: refresh should use remote server expiration time for nse

pkg/registry/common/expire/ns_server.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go
If the next of the `expire` chain element do remote register then `expire` not set the expiration time for the response.
=> fix: expire registry chain element should correctly set expiration time

pkg/registry/common/interpose/client.go, pkg/registry/common/interpose/doc.go, pkg/registry/common/interpose/name.go, pkg/registry/common/interpose/server.go, pkg/registry/common/interpose/server_test.go
`recvfd`, `expire` works incorrectly due to the interpose rename.
Stop renaming interpose.
=> Stop renaming interpose NSE

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/registry/common/refresh/options.go, pkg/registry/utils/checks/checknse/doc.go, pkg/registry/utils/checks/checknse/nse_client.go, pkg/registry/utils/checks/checknse/nse_server.go
1. `refresh` uses name from client.
2. `startRefresh` overrides initial URL with returned from server.
3. `startRefresh` should fail on error returned from server.
4. Tests wait for incorrect `requestCount`.
1. Always override only name and expiration time with returned from server.
2. Same.
3. Stop retrying to refresh on error returned, log a warning message.
4. Fix tests.
=> Fix registry refresh

pkg/registry/common/dnsresolve/common.go
There is no need to call resolver if domain is already in `tcp://${addr}:${port}` format.
=> Don't call resolver if domain is already resolved

pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go
Fixes ci here : https://github.com/networkservicemesh/cmd-registry-memory/pull/183
=> fix: registry expiration logic doesn't work

pkg/networkservice/chains/nsmgr/server_test.go, pkg/networkservice/common/discover/server.go
`discover` chain element don't read fully channel from `registry.ReadNetworkServiceEndpointChannel` - it results in #619.
Use GRPC Stream instead of channels.
Closes #619.
=> Fix NS watch

pkg/networkservice/chains/nsmgr/server_test.go, pkg/registry/common/querycache/nse_client.go, pkg/registry/common/querycache/nse_client_test.go, pkg/tools/sandbox/utils.go
1. Query cache starts watching Find on chain context, it lasts until the application closes.
2. There is a possible leak when registry deletes NSE in process of cache Find.
1. Start watching Find on special context and close it after NSE remove.
2. Double check that NSE exists in registry before starting to wait events for it.
=> Fix query cache goleaks

pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
Registry doesn't use strict name match for NS, NSE find. Discover can receive NS/NSE with invalid name and pass it further to the chain.
Make extra name check for NS, NSE on discover.
=> Discover should use strict name match

pkg/tools/nsmlabel/nsmlabel.go, pkg/tools/nsmlabel/nsmlabel_test.go
Currently, cmd-nsc config looks over-designed: https://github.com/networkservicemesh/cmd-nsc/blob/master/internal/config/config.go#L47
Moreover, this approach is not expandable. For building new NSC we need to copy a lot of stuff from cmd-nsc.
We should seek to make things simple.
This PR is the first part of reworking cmd-nsc.
=> feat: add nsmlabel tool to help developers build NSCs

pkg/networkservice/core/trace/client.go, pkg/networkservice/core/trace/common_test.go, pkg/networkservice/core/trace/server.go
=> Fix trace diffs

pkg/registry/common/sendfd/client_linux.go, pkg/registry/common/sendfd/client_linux_test.go
`sendfd` NSE registry client doesn't call next `Unregister`.
Fix it.
=> Make sendfd NSE registry client call next Unregister

pkg/registry/common/memory/ns_server.go, pkg/registry/common/memory/ns_server_test.go, pkg/registry/common/memory/nse_server.go, pkg/registry/common/memory/nse_server_test.go
There are data races, deadlocks and invalid behavior in both NSE, NS memory registry servers.
1. Add unit tests for data races, slow receiver, all Register/Unregister received.
2. Rework NSE, NS memory registry servers.
=> Rework memory registry server

go.mod, pkg/networkservice/common/mechanisms/client.go, pkg/networkservice/common/mechanisms/client_test.go, pkg/networkservice/common/mechanisms/common.go, pkg/networkservice/common/mechanisms/server.go
1. This PR adds mechanisms client that can be used in nsc applications to simplify chains.
For example:
This https://github.com/networkservicemesh/cmd-nsc/blob/master/main.go#L125-L185 can be replaced to
```go
client.NewClient(..., 
mechanisms.NewClient(map[string]networkservice.NetworkServiceClient {
vfio.MECHANISM: chain.NewNetworkServiceClient(...),
kernel.MECHANISM: chain.NewNetworkServiceClient(...),
})
```
2. It Fixes a few issues like adding the same error in error: https://github.com/networkservicemesh/sdk/blob/master/pkg/networkservice/common/mechanisms/server.go#L74
3. Removes recurrent dependency.
=> feat: Add mechanisms client

pkg/registry/common/refresh/nse_registry_client_test.go
```
==================
WARNING: DATA RACE
Read at 0x00c00000e0e0 by goroutine 20:
github.com/networkservicemesh/sdk/pkg/registry/common/refresh_test.Test_RefreshNSEClient_ShouldOverrideNameAndDuration.func1()
/Users/runner/work/sdk/sdk/pkg/registry/common/refresh/nse_registry_client_test.go:126 +0x5e
github.com/networkservicemesh/sdk/pkg/registry/utils/checks/checknse.(*checkNSEClient).Unregister()
/Users/runner/work/sdk/sdk/pkg/registry/utils/checks/checknse/nse_client.go:56 +0x8a
github.com/networkservicemesh/sdk/pkg/registry/core/next.(*nextNetworkServiceEndpointRegistryClient).Unregister()
/Users/runner/work/sdk/sdk/pkg/registry/core/next/nse_registry_client.go:73 +0x5b7
github.com/networkservicemesh/sdk/pkg/registry/common/refresh.(*refreshNSEClient).Unregister() …
```
=> Fix data race in refresh test

pkg/registry/common/memory/common_test.go, pkg/registry/common/memory/ns_server.go, pkg/registry/common/memory/ns_server_test.go, pkg/registry/common/memory/nse_server.go, pkg/registry/common/memory/nse_server_test.go
Sometimes `TestNetworkServiceEndpointRegistryServer_ShouldReceiveAllRegisters`, `TestNetworkServiceEndpointRegistryServer_ShouldReceiveAllUnregisters` fail due to the huge amount of NSEs, low timeout.
Reduce amount, increase timeout.
=> Fix memory tests

pkg/networkservice/chains/nsmgr/server_test.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/utils.go
`expire` timeout is too small for windows, macos - sometimes endpoint becomes unregistered.
Increase timeout for most sandbox tests.
Closes #710
=> Fix TestNSMGR_PassThroughLocal

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/client_test.go
This PR fixes kernel client for #721
=> fix: kernel client should not add new mechanism if kernel mechanism already added into preference list

pkg/networkservice/chains/client/client.go, pkg/networkservice/common/authorize/client.go, pkg/tools/opa/last_token_signed_policy.go, pkg/tools/opa/last_token_signed_policy_test.go
authorize client should check tokens on backward because on forward it have not server's cert and also it will cover much more cases.
=> fix: authorize client should check tokens on backward

.github/workflows/ci.yaml
go 1.15.8 has fixes for some major issues (for example issue with `time.After` on Windows platform)
Signed-off-by: Artem Belov <artem.belov@xored.com>
=> Update go-version 1.15.8 for github workflows

pkg/registry/common/expire/nse_server.go
Closes #742.
Unregister timer should set `started` flag on start.
=> Fix NSE registry expire refresh failure case

pkg/tools/timer/timer.go, pkg/tools/timer/timer_test.go
There is an issue with `time.AfterFunc` and `time.Timer` returned from there:
* if `Timer.Stop()` returns `false`, there is no way to get information about function status - we only knows that it has been started in some time before.
Close `Timer.C` on successful `Timer.Stop` or function return. Now we can use such code to make sure that no timer logic is more executing:
```go
if !timer.Stop() {
<-timer.C
}
// Here we know that function hasn't been started or already has been finished.
```
=> Add timer.AfterFunc

.golangci.yml, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/common/discover/server_test.go, pkg/registry/chains/memory/server.go, pkg/registry/common/interpose/server.go, pkg/registry/common/interpose/server_test.go, pkg/registry/common/setid/server.go, pkg/registry/common/setid/server_test.go, pkg/registry/core/interdomain/interdomain_ns_test.go, pkg/registry/core/interdomain/interdomain_nse_test.go
Closes #726.
1. Set `nse.Name` on backward if it is unchanged.
2. `interpose` should generate unique names by itself.
=> Rework setid to call on backward

pkg/tools/log/logruslogger/logruslogger.go
`logruslogger.New` and `logruslogger.FromSpan` overwrite logs time with `time.Now`. So for any prolonged usage of this logger we get same timestamps for all logs.
Stop using `.WithTime(time.Now())` and let logs to use their own timestamps.
=> Logrus logger shouldn't overwrite time for logs

pkg/networkservice/chains/nsmgrproxy/server.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
Refactor `chains/nsmgrproxy` to use Option pattern
Closes #736.
Signed-off-by: Anatoly Loskutnikov <anatoly.loskutnikov@gmail.com>
=> Refactor chains/nsmgrproxy to use Option pattern

pkg/networkservice/common/connect/server.go, pkg/networkservice/common/connect/server_test.go
Fixes example:
If forwarder cannot setup mechanism, already opened connection should be closed
Signed-off-by: Artem Belov <artem.belov@xored.com>
=> Close connection in connect on next.Request error

pkg/registry/chains/memory/server.go
Refers to #770.
It is incorrect to use `checkid` before `expire` - there will be memory leaks for the expired endpoints.
=> [sdk#770] Set checkid before expire

pkg/networkservice/chains/nsmgr/nsmgr_test.go
This line was accidentally removed in https://github.com/networkservicemesh/sdk/pull/806.
=> Return accidentally removed goleak check

pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go
Fixes coredns restarting for webhook example
```
loading Caddyfile via flag: open /etc/coredns/Corefile: no such file or directory
```
Currently, coredns config creating too long, and coredns container could be restarted few times...
=> qfix: dnsClient should configure coredns file on starting to prevent coredns failure

pkg/networkservice/common/discover/server_test.go, pkg/networkservice/common/journal/server_test.go, pkg/networkservice/common/refresh/client_test.go, pkg/networkservice/common/timeout/server_test.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/querycache/nse_client_test.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/tools/clockmock/mock.go, pkg/tools/clockmock/mock_test.go, pkg/tools/clockmock/timer.go
#764
If code uses timer added with 0 duration, it will never fire in test with `clockmock.Mock` until time will be modified.
Make time in `clockmock.Mock` always running but slowed down at 100000 times.
Closes https://github.com/networkservicemesh/sdk/issues/865.
=> Edit clockmock.Mock to slowly run time all the time

.github/workflows/update-dependent-repositories-gomod.yaml
Condition `github.event_name == 'push'` is more strict then `github.ref == 'refs/heads/main`
=> fix: Improve condition for 'Update dependent repositories' job

pkg/networkservice/common/heal/client.go
Check if connection is active before healing.
Closes https://github.com/networkservicemesh/sdk/issues/902.
=> Stop double healing connections

pkg/registry/common/localbypass/find_server.go, pkg/registry/common/localbypass/server_test.go
Currently, localbypass cannot recognize the endpoint that has registered in the floating registry.
These changes needed to https://github.com/networkservicemesh/sdk/issues/853
=> fix: localbypass should correctly work in case of register in the floating registry

pkg/registry/common/querycache/nse_client.go
Adds missed NSE clone on return in `querycache`.
```
2021-05-13T06:34:36.2512451Z ==================
2021-05-13T06:34:36.2512901Z WARNING: DATA RACE
2021-05-13T06:34:36.2513439Z Read at 0x00c000970c98 by goroutine 21:
...
2021-05-13T06:34:36.2526316Z   github.com/networkservicemesh/api/pkg/api/registry.(*NetworkServiceEndpoint).Clone()
2021-05-13T06:34:36.2527457Z       C:/Users/runneradmin/go/pkg/mod/github.com/networkservicemesh/api@v0.0.0-20210509180413-5753c9f30588/pkg/api/registry/helpers.go:101 +0xd7
2021-05-13T06:34:36.2528765Z   github.com/networkservicemesh/sdk/pkg/registry/common/querycache.(*queryCacheNSEClient).findInCache()
...
2021-05-13T06:34:36.2622739Z Previous write at 0x00c000970c98 by goroutine 102:
2021-05-13T06:34:36.2623804Z …
```
=> [qfix] Fix data race caused by querycache

pkg/networkservice/common/discover/server_test.go, pkg/networkservice/common/journal/server_test.go, pkg/networkservice/common/onidle/server_test.go, pkg/networkservice/common/refresh/client_test.go, pkg/networkservice/common/timeout/server_test.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/querycache/nse_client_test.go, pkg/registry/common/refresh/nse_registry_client_test.go, pkg/tools/clockmock/mock.go, pkg/tools/clockmock/mock_test.go, pkg/tools/clockmock/ticker.go, pkg/tools/clockmock/timer.go
1. Add clockmock Start (needed for the discover stage in sandbox tests).
2. Fix clocmock race issues.
Relates to #898.
=> [sdk#898] Add clockmock Start

pkg/networkservice/chains/nsmgr/scale_test.go, pkg/networkservice/common/discover/server_test.go
Add test specified in the linked issue, fix things that prevented this test from working.
Fixes https://github.com/networkservicemesh/sdk/issues/916
=> Add test checking registering endpoint for alt match during request

.golangci.yml, pkg/networkservice/common/clientinfo/client_test.go, pkg/registry/common/clientinfo/server_test.go, pkg/tools/clientinfo/clientinfo.go
Currently `clientinfo` overwrites labels that are already present. This is incorrect behaviour because this way local NS manager which contains `clientinfo` element will overwrite labels with its local values, rendering `clientinfo` useless, because we already know our local values and we want to know where the request came from.
This PR makes `clientinfo` skip already present values and changes the unit tests to accommodate for this change (for both `networkservice`'s and `registry`'s `clientinfo` element).
=> [qfix] Make clientinfo skip already preset labels

pkg/registry/chains/client/nse_client.go
Moves `sendfd` chain element to the client chain after `connect`.
sdk#713
=> [sdk#713] registry connect (fix)

pkg/networkservice/common/heal/client.go
gRPC requests and streaming requests have different requirements for the underlying gRPC connection. There can be a case on the closing gRPC connection, when it is still sending requests but fails to keep or start a streaming request. In such case we can get a situation when we have a Connection with no monitor stream, so it would never be healed.
We should check that monitor stream is ready for the Connection, before returning it back. This check should wait for some time after the next.Request(), because for the [NSMgr -> Endpoint] case response may come faster than monitor stream update.
https://github.com/networkservicemesh/sdk/issues/925
=> [sdk#925] Add waiting for the monitor updates

pkg/networkservice/common/heal/client.go
Missed this in the initial PR https://github.com/networkservicemesh/sdk/pull/926#discussion_r635858267.
#925
=> [sdk#925] Replace time.After() with waiting on client context done

pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/chains/nsmgr/utils_test.go, pkg/networkservice/common/replacelabels/client.go, pkg/networkservice/utils/inject/injectlabels/client.go, pkg/tools/sandbox/utils.go
With this changes passthrough cases now using labels matching to discover endpoint chain, also added case for testing multi label scenario
fixes https://github.com/networkservicemesh/sdk/issues/880
=> Rework of sandbox passthrough tests for using matches

pkg/networkservice/common/heal/server.go
Restore shouldn't start heal if heal context is canceled.
=> [qfix] Don't start healing if ctx is canceled

pkg/networkservice/common/connect/README.md, pkg/networkservice/common/connect/client.go, pkg/networkservice/common/connect/monitor_client_test.go, pkg/networkservice/common/connect/server.go, pkg/networkservice/common/connect/server_test.go, pkg/networkservice/common/connect/utils_test.go, pkg/networkservice/common/heal/client.go, pkg/tools/cancelctx/context.go
gRPC stream handles gRPC connection state change faster than our existing check and so we can have monitor stream closed, but connect client still running.
Use monitor stream to track gRPC connection liveness.
#925
=> [sdk#925] Use monitor stream for canceling connect client

pkg/tools/clockmock/mock_test.go
Clock mock set speed tests requires too high precision.
=> [qfix] Reduce clockmock set speed test precision

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/heal/option.go, pkg/networkservice/common/heal/server.go, pkg/networkservice/common/heal/server_test.go, pkg/tools/sandbox/node.go
Reworks heal server to options, adds `restoreEnabled` option.
#970
=> [sdk#970] Add restoreEnabled option to heal

pkg/tools/sandbox/node.go
Use default sandbox dial timeout `500ms` instead of default `100ms` for sandbox NSC.
=> Use default sandbox dial timeout for sandbox NSC

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/common/heal/option.go, pkg/networkservice/common/heal/server.go, pkg/tools/sandbox/node.go
Makes restore disabled in heal by default. Enables restore only in client by default.
#978
=> [sdk#978] Disable restore in heal

pkg/registry/common/setid/client.go, pkg/registry/common/setid/client_test.go
Use `grpcutils.UnwrapCode` instead of `status.Code` in `setid`.
https://github.com/networkservicemesh/integration-k8s-aks/pull/53
=> [qfix] Use grpcutils.UnwrapCode in setid

pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go
Adds timeout for `discoverNetworkServiceEndpoint`.
https://github.com/networkservicemesh/integration-k8s-kind/runs/2855694310
=> [qfix] Add timeout for discoverNetworkServiceEndpoint

pkg/networkservice/common/onidle/server_test.go
fixes https://github.com/networkservicemesh/sdk/issues/988
=> Fix unstable tests in onidle package

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/scale_test.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/chains/nsmgr/utils_test.go, pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/networkservice/common/connect/server_cancel_test.go, pkg/networkservice/common/refresh/client_test.go, pkg/registry/chains/memory/server_test.go, pkg/registry/chains/proxydns/server_ns_test.go, pkg/registry/chains/proxydns/server_nse_test.go, pkg/registry/common/heal/find_test.go, pkg/tools/sandbox/README.md, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/grpc_utils.go, pkg/tools/sandbox/grpc_utils_notwindows.go, pkg/tools/sandbox/grpc_utils_windows.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/types.go, pkg/tools/sandbox/utils.go
Sandbox rework for #740. Corresponding heal tests rework.
Changes:
1. adds `Node.NewNSMgr`
2. all `sandbox` methods now handle errors inside with `require.NoError`
3. removes `Builder.SetCustomConfig` - replaces it with extended `Builder.SetNodeSetup`
4. removes `Domain.resources` - every resource now has a goroutine waiting on the corresponding context
5. adds `.Name` to `NSMgrEntry`, `EndpointEntry` to enable emulation of `NSMgr`/`Forwarder`/`Endpoint` restart with same name + URL
6. removes `Node.Forwarder` - forwarder can be accessed after custom creation in `Builder.SetNodeSetup`
=> [sdk#740] Rework sandbox

pkg/tools/clockmock/mock_test.go
Increase timeout for clockmock tests.
#993
=> [sdk#993] Fix TestMock_AfterFunc

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/common/heal/server.go
Current request duration in not enough for healing.
=> fix: use max of ctx.deadline and requestDuration for healing

pkg/tools/resetting/transport_credentials.go, pkg/tools/resetting/transport_credentials_test.go
Part of https://github.com/networkservicemesh/deployments-k8s/issues/1929
To complete the issue we need also update each NSM repo.
=> fix: Add possible for long-living grpc connections to update expired certificates

pkg/registry/common/refresh/nse_registry_client.go, pkg/registry/common/refresh/nse_registry_client_test.go
Currently, nses cannot be refreshed in the floating interdomain scenario. 
This PR fixes the issue.
=> fix: registry/refresh clients doesn't refresh NSEs registration in case of floating interdomain

pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/common/discover/match_selector.go
Fix for match selector which enables continuation in case of absent nse candidates
part of https://github.com/networkservicemesh/deployments-k8s/issues/2007
blocked by https://github.com/networkservicemesh/api/pull/106
=> Added fallthrough check in matching

pkg/networkservice/chains/client/client_heal_test.go, pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/networkservice/common/connect/server_cancel_test.go, pkg/registry/common/connect/ns_client_test.go, pkg/registry/common/connect/nse_client_test.go, pkg/registry/common/heal/find_test.go, pkg/tools/grpcutils/url.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/grpc_utils.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/restartable_server.go, pkg/tools/sandbox/types.go
Makes sandbox entries cancelable and restartable:
* `RegistryEntry`
* `NSMgrEntry`
* `EndpointEntry`
#999
=> [sdk#999] Make sandbox entries restartable

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/common/discover/server.go, pkg/networkservice/common/discover/server_test.go, pkg/networkservice/common/roundrobin/server.go
Adds `Close` propagation for `discover` for not existing (probably expired) NSE case.
networkservicemesh/deployments-k8s#2003
=> [deployments-k8s#2003] Add discover close for expired NSE

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/kernel/utils.go, pkg/networkservice/common/mechanismtranslation/client_test.go
https://github.com/networkservicemesh/sdk-vpp/issues/254
Set default name for kernel interface
=> Set default kernel interface name

go.mod, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/swapip/server.go, pkg/networkservice/common/swapip/server_test.go, pkg/registry/common/swapip/nse_registry.go, pkg/registry/common/swapip/nse_registry_test.go, pkg/registry/utils/checks/checknse/nse_server.go
https://github.com/networkservicemesh/sdk/issues/1015
=> fix: NSE registrations could have internal IPs in floating registry

pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/refresh/client_test.go
Disable refresh if request fails.
#809
=> [sdk#809] Refresh should not happen after failed request

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/utils.go
Limit kernel interface name.
Moved from api.
https://github.com/networkservicemesh/api/pull/108/
=> Limit kernel interface name

pkg/registry/common/swapip/nse_registry_test.go
Fixes SwapIPNSERegistry tests instability.
https://github.com/networkservicemesh/sdk/runs/3063203054?check_suite_focus=true#step:5:100
=> qfix: Stabilize SwapIPNSERegistry tests

pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/registry/common/dnsresolve/common.go, pkg/registry/common/dnsresolve/nse_server.go, pkg/registry/common/dnsresolve/nse_server_test.go
Problem scenario:
1. NSE "nse-1@floating" registers in the floating domain with labels: `"ns-1@floating" : {"app": "myapp"}`.
2. NSE "nse" registered in floating registry with labels: `"ns-1@floating" : {"app": "myapp"}`
3. Call Find request "nse-1@floaing" on local registry.
Actual: Returned **nse-1** with  labels: "ns-1@floating" : {"app": "myapp"}
Expected: Returned **nse-1@floating** with  labels: "ns-1@floaitng" : {"app": "myapp"}
=> qfix: DNSNSEResolve server should correctly translate NSE for floating side and for querying side

pkg/networkservice/utils/metadata/client.go, pkg/networkservice/utils/metadata/context.go, pkg/networkservice/utils/metadata/meta_data_test.go, pkg/networkservice/utils/metadata/server.go
Fixes `metadata.Map(ctx)` panic on double Close.
Related to kind integration tests failure - https://github.com/networkservicemesh/integration-k8s-kind/runs/3136678807?check_suite_focus=true.
=> [qfix] Fix panic on metadata chain elements double Close

pkg/networkservice/common/connect/server.go
Default `100ms` dial timeout is too low sometimes, increased to `1s`.
Related to kind integration tests failure - https://github.com/networkservicemesh/integration-k8s-kind/runs/3136678807?check_suite_focus=true.
=> [qfix] Increase default dial timeout to 1 second

pkg/networkservice/utils/metadata/client.go, pkg/networkservice/utils/metadata/meta_data_test.go, pkg/networkservice/utils/metadata/server.go
Fixes invalid cleanup  in metadata.
Relates to https://github.com/networkservicemesh/integration-k8s-kind/pull/333 failing.
=> [qfix] Fix metadata cleanup

.github/workflows/update-dependent-repositories-gomod.yaml
sdk-vpp is now updated by sdk-kernel.
=> Don't directly update sdk-vpp

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/scale_test.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/chains/nsmgr/utils_test.go, pkg/networkservice/common/connect/server_test.go, pkg/networkservice/common/heal/heal_test.go, pkg/networkservice/common/interpose/server_test.go, pkg/networkservice/utils/count/client.go, pkg/networkservice/utils/count/doc.go, pkg/networkservice/utils/count/server.go
Extracts `count` chain element to `networkservice/utils`.
Needed for #1039.
=> [sdk#1039] Move counter chain element to networkservice/utils

pkg/tools/log/spanlogger/spanlogger.go
It seems we don't actually need `debug.Stack()`, because `errors.New()` already [has a stack](https://github.com/pkg/errors/blob/master/errors.go#L68-L73): 
```
// New, Errorf, Wrap, and Wrapf record a stack trace at the point they are
// invoked. This information can be retrieved with the following interface:
//
//     type stackTracer interface {
//             StackTrace() errors.StackTrace
//     }
```
Even if we create `error` without  using `errors` package, `trace` chain element will wrap it to the struct with stack trace (`errors.Wrapf(...)`).
We do not need to call `debug.Stack()` for every `Errorf()` call, because we already have this information.
And we need to set `"%+v"`  if we want to print error with stack trace - …
=> Remove debug.Stack() from logger

pkg/networkservice/chains/client/client_heal_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/networkservice/common/connect/server_cancel_test.go, pkg/registry/chains/memory/server_test.go, pkg/registry/common/heal/find_test.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/dial_options.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/types.go, pkg/tools/sandbox/utils.go
Reworks `sandbox.DefaultDialOptions` to `sandbox.DialOptions` with options pattern.
Needed for networkservicemesh/deployments-k8s#2393.
=> [deployments-k8s#2393] Rework sandbox.DefaultDialOptions to sandbox.DialOptions with options

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/client/client_heal_test.go
Puts `heal` client after all other chain elements, right before `networkservice.NewNetworkServiceClient(cc)` in client, client factory chains.
Depends on https://github.com/networkservicemesh/sdk/pull/1056.
Closes #1039.
=> [sdk#1039] Reorder client chain elements

pkg/networkservice/chains/client/client_heal_test.go
=> qfix: Fix dial options in client heal test

.golangci.yml, pkg/networkservice/core/next/client.go, pkg/networkservice/core/next/server.go, pkg/networkservice/core/next/tests/client_test.go, pkg/networkservice/core/next/tests/server_test.go, pkg/registry/core/next/ns_registry_client.go, pkg/registry/core/next/ns_registry_server.go, pkg/registry/core/next/ns_registry_server_test.go, pkg/registry/core/next/nse_registry_client.go, pkg/registry/core/next/nse_registry_server.go, pkg/registry/core/next/nse_registry_server_test.go
Add support for empty subchains (networkservice, NS registry, NSE registry):
```go
var serversA, serversB, serversC []networkservice.Server
...
server := chain.NewServer(
chain.NewServer(serversA...), // <-- now can be empty
chain.NewServer(serversB...), // <-- now can be empty
chain.NewServer(serversC...), // <-- now can be empty
)
```
Needed for networkservicemesh/sdk-vpp#314.
=> [sdk-vpp#314] Support empty chains

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/client/client_heal_test.go
In heal we are taking the right most connection and trying to use it for the left most chain element, so how it looks in Forwarder chain:
```
... -> mechanisms server -> ... -> mechanism translation client -> ... -> heal client -> gRPC client
```
Until #1039 it was slightly different:
```
... -> mechanisms server -> ... -> heal client -> mechanism translation client -> ... -> gRPC client
```
1. `heal` tries to close server chain using client mechanism
2. instead of closing `kerneltap` and cleaning kernel interface, it closes `vxlan` and just does nothing
3. upcoming Request fails when trying to create a new kernel interface with already existing name
Doesn't look like we can easily solve this issue without a `begin` chain element, so we probably can revert some last changes and wait for …
=> [qfix] Fix client chain order

pkg/networkservice/common/monitor/filter.go, pkg/networkservice/common/monitor/server.go, pkg/networkservice/common/monitor/server_test.go, pkg/networkservice/core/adapters/monitor_server_to_client.go, pkg/networkservice/core/eventchannel/monitor_connection_server.go
Creates separate executors for sending events to different monitor clients.
Closes #1042.
=> [sdk#1042] Fix monitor blocking sending events on non-reading client

pkg/networkservice/common/authorize/client.go, pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_test.go, pkg/networkservice/common/heal/server.go, pkg/tools/opa/next_token_signed_policy_test.go, pkg/tools/opa/policies.go, pkg/tools/opa/policies/next_token_signed.rego
https://github.com/networkservicemesh/sdk/pull/1018 was outdated with the main branch.  
For example, 
1. path.Index for the client in the main branch for the first client is 0 (previously it was 1).
2. heal can trigger authrorize server without peer in the context. In this case authorizer server shoudl allow the request.
Fixes https://github.com/networkservicemesh/integration-k8s-kind/pull/354
=> fix: Actualise authorize server with latest main branch changes

pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go, pkg/tools/dnscontext/manager.go, pkg/tools/dnscontext/manager_test.go
Use coredns `cache` plugin.
networkservicemesh/deployments-k8s#2689
=> [deployments-k8s#2689] Use DNS cache plugin

pkg/networkservice/chains/endpoint/combine.go, pkg/networkservice/chains/endpoint/combine_monitor_server.go, pkg/networkservice/chains/endpoint/combine_test.go
Adds a new utility method to merge multiple `endpoint.Endpoint` in a single one.
Example of usage to merge SR-IOV forwarder and VPP forwarder endpoints in a single one - https://github.com/networkservicemesh/cmd-forwarder-vpp/blob/d50f7aab7dde0350e91509eb182784dc3b6a29fb/internal/xconnectns/server.go
networkservicemesh/sdk-vpp#314
=> [sdk-vpp#314] Add endpoint.Combine

pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/refresh/client_test.go
Add refresh retries on failure.
=> [qfix] Add refresh retries on failure

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/option.go
Adds `WithEndpointChange` heal option to be enabled only on NSC.
=> [qfix] Add WithEndpointChange heal option

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
now cmd-nse-icmp-responder is made as dependent to sdk-sriov, so now this is redundant.
Signed-off-by: Periyasamy Palanisamy <periyasamy.palanisamy@est.tech>
=> remove cmd-nse-icmp-responder as dependent repo

.golangci.yml, pkg/networkservice/common/retry/client.go, pkg/networkservice/common/retry/client_test.go
https://github.com/networkservicemesh/sdk/issues/1123
=> feat: Add "retry" networkservice.Client wrapper for nscs

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/unix_test.go
=> qfix: memory registry should be used directly in nsmgr on discovering forwarders

pkg/networkservice/chains/client/client.go, pkg/networkservice/chains/client/options.go, pkg/networkservice/chains/endpoint/server.go, pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/common/begin/client.go, pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/begin/merge.go, pkg/networkservice/common/begin/options.go, pkg/networkservice/common/begin/server.go, pkg/networkservice/common/dial/dialer.go, pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/client_filter.go, pkg/networkservice/common/heal/doc.go, pkg/networkservice/common/heal/eventloop.go, pkg/networkservice/common/heal/metadata.go, pkg/networkservice/common/heal/options.go, pkg/networkservice/common/trimpath/client.go, pkg/networkservice/common/trimpath/doc.go, pkg/networkservice/common/trimpath/metadata.go, pkg/networkservice/common/trimpath/server.go, pkg/networkservice/common/trimpath/trimpath_test.go, pkg/tools/sandbox/dial_options.go, pkg/tools/sandbox/node.go
This PR adds new healing feature
Continuation of https://github.com/networkservicemesh/sdk/pull/1107
=> Add healing feature

pkg/networkservice/chains/nsmgr/single_test.go
Fixes broken tests in sdk
closes https://github.com/networkservicemesh/sdk/issues/1160
=> Fixed broken tests

pkg/networkservice/core/trace/common_test.go, pkg/tools/log/logruslogger/logruslogger.go
Log level trace was hardcoded for unknown reasons. It caused always setting log level to trace no matter what was passed from config in `cmd`.
closes https://github.com/networkservicemesh/cmd-nsmgr/issues/417
=> Fix in level setting for log

pkg/networkservice/common/begin/event_factory.go
We need to use old path for heal request to check resources from a previous connection 
https://github.com/networkservicemesh/sdk/issues/1166
=> heal: use path from previous connection

pkg/networkservice/common/mechanisms/vxlan/vni/server.go
We need to delete `vni` on error only if we generated it on that `Request`
Fixes: https://github.com/networkservicemesh/integration-k8s-packet/issues/166
=> [qfix] Delete only generated vxlan vni on error

pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discoverforwarder/server.go
Currently discover is not supported matches with empty routes but with metadata.
https://github.com/networkservicemesh/integration-k8s-kind/pull/505
=> qfix: Add support for empty routes with metadata

pkg/networkservice/common/heal/client.go, pkg/networkservice/common/heal/client_filter.go, pkg/networkservice/common/heal/eventloop.go
Added logs to healClient to to localize this problem:
https://github.com/networkservicemesh/integration-k8s-packet/issues/185
=> Add logs to healClient

pkg/networkservice/common/refresh/client.go, pkg/networkservice/common/refresh/client_test.go, pkg/networkservice/common/timeout/server_test.go
Signed-off-by: Oleg Solodkov <oleg.solodkov@xored.com>
Refresh client calculates the shortest token expiry and sets refresh time according to that value
Fixes #1189
=> Modified refresh client to calculate the shortest token expiry

pkg/networkservice/common/cidr/cidr_test.go, pkg/networkservice/common/cidr/client.go, pkg/networkservice/common/cidr/doc.go, pkg/networkservice/common/cidr/metadata.go, pkg/networkservice/common/cidr/server.go, pkg/tools/prefixpool/prefixpool.go
This chain element extracts prefix from some global prefix and writes it to `ExtraPrefixes` - [Link](https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/connectioncontext.proto#L65) 
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/1
=> Add cidr chain element

pkg/networkservice/common/discoverforwarder/server.go
Remove forwarder name from discoverforwarder metadata if it is not available
For example, heal case :
`nsc -> nsmgr1(restarted) -> fwd1 -> nsmgr2 -> fwd2(restarted) -> nse`
If `nsmgr1` dies, `nsmgr2` doesn't receive `Close()` and continues to store old `fwd2` name in metadata
https://github.com/networkservicemesh/sdk/issues/1196
=> Remove forwarder name from discoverforwarder metadata

pkg/registry/common/retry/nse_client.go
We should use the cloned element for registry `retry`, because a previous attempt can change something inside
https://github.com/networkservicemesh/integration-k8s-kind/pull/537
=> [qfix] Use cloned nse in retry registry

.github/workflows/ci.yaml, pkg/networkservice/chains/nsmgr/unix_test.go, pkg/networkservice/common/mechanisms/kernel/vlan/server.go, pkg/networkservice/common/mechanisms/recvfd/client.go, pkg/networkservice/common/mechanisms/recvfd/common.go, pkg/networkservice/common/mechanisms/recvfd/server.go, pkg/networkservice/common/mechanisms/recvfd/server_test.go, pkg/networkservice/common/mechanisms/sendfd/client.go, pkg/networkservice/common/mechanisms/sendfd/common.go, pkg/networkservice/common/mechanisms/sendfd/server.go, pkg/networkservice/common/roundrobin/server.go, pkg/registry/common/dnsresolve/common.go, pkg/registry/common/recvfd/client.go, pkg/registry/common/recvfd/server.go, pkg/registry/common/recvfd/server_test.go, pkg/registry/common/sendfd/client_linux.go, pkg/registry/common/sendfd/client_linux_test.go, pkg/registry/common/sendfd/server_linux.go, pkg/tools/fs/inode.go, pkg/tools/grpcfdutils/transceiver.go, pkg/tools/opa/policy.go, pkg/tools/prefixpool/prefixpool.go, pkg/tools/sandbox/grpc_utils_notwindows.go
Updated golangci-lint to 1.42.1 and fixed linter errors
Signed-off-by: Oleg Solodkov oleg.solodkov@xored.com
=> Updated golangci-lint version, fixed linter errors

pkg/tools/jaeger/exporter.go, pkg/tools/log/logger.go, pkg/tools/log/spanlogger/spanlogger.go, pkg/tools/opentelemetry/exporter.go, pkg/tools/opentelemetry/opentelemetry.go, pkg/tools/tracing/grpcoptions.go, pkg/tools/zipkin/exporter.go
=> Open Telemetry minor fix

pkg/networkservice/common/policyroute/doc.go, pkg/networkservice/common/policyroute/server.go, pkg/networkservice/common/policyroute/server_test.go
This PR adds `policyroute` chain element to implement Policy Based Routing.
It will put policies in connection context on the NSE side.
https://github.com/networkservicemesh/api/issues/119
=> Add policyroute chain element

pkg/networkservice/chains/nsmgr/server.go, pkg/registry/chains/client/ns_client.go, pkg/registry/chains/client/nse_client.go, pkg/tools/sandbox/node.go
```
client_endpoint_test.go:173: 
Error Trace:	client_endpoint_test.go:173
Error:      	Expected nil, but got: Error returned from sdk/pkg/networkservice/common/connect/connectClient.Request: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Test:       	TestRegistryTestSuite/TestNSmgrEndpointSendFD
Jan 26 17:59:35.707[31m [ERRO] [id:2d635a07-e687-48a9-8a9a-283d8a05449a] [type:networkService] [0m(60.1)                                                              rpc error: code = Canceled desc = grpc: the client connection is closing;	Error returned from sdk/pkg/networkservice/common/connect/connectClient.Request;	github.com/networkservicemesh/sdk/pkg/networkservice/core/trace.logError; …
```
=> qfix: sendfd registry cases are not working

pkg/networkservice/chains/nsmgr/server.go, pkg/tools/sandbox/node.go
regDialOptions are not used more.
=> Refactor: nsmgr WithrRgistry option has useless registry dial options

pkg/networkservice/chains/nsmgr/server.go
The current localbypass order is not correct.
Actual:
```
Jan 27 17:56:54.379[37m [TRAC] [type:registry] [0m(18.1)                    network service endpoint={"name":"forwarder-vpp-pt2q7","network_service_names":["forwarder"],"network_service_labels":{"forwarder":{"labels":{"nodeName":"kind-worker","p2p":"true"}}},"url":"tcp://10.244.1.20:5001","expiration_time":{"seconds":1643306254,"nanos":137086614},"initial_registration_time":{"seconds":1643306194,"nanos":143158306}}
Jan 27 17:56:54.379[37m [TRAC] [type:registry] [0m(23)                       ⎆ api/pkg/api/registry/networkServiceEndpointRegistryFindClient.Recv()
Jan 27 17:56:54.379[37m [TRAC] [type:registry] [0m(17)                 ⎆ …
```
=> qfix: Localbypass is not working properly in integration-tests scenarious

pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/registry/chains/proxydns/server_ns_test.go, pkg/registry/common/dnsresolve/ns_server.go, pkg/registry/common/dnsresolve/nse_server.go
Previously we reworked the registry https://github.com/networkservicemesh/sdk/pull/1213.
This conceptually fixes https://github.com/networkservicemesh/cmd-registry-k8s/issues/250 but during testing it, I found a few missed nits in https://github.com/networkservicemesh/sdk/pull/1213.
This PR covers case https://github.com/networkservicemesh/cmd-registry-k8s/issues/250 and fixes it.
Fixes https://github.com/networkservicemesh/cmd-registry-k8s/issues/250
=> fix: Issue when register endpoints with same name

pkg/registry/common/dial/ns_client.go, pkg/registry/common/dial/nse_client.go
Memory profile for 100 refreshes before the fix is:
[Before fix.pdf](https://github.com/networkservicemesh/sdk/files/8045106/no-fix.pdf)
Memory profile for 100 refreshes after the fix is:
[After fix.pdf](https://github.com/networkservicemesh/sdk/files/8045107/fix.pdf)
=> fix: remove leaking of client connections on find queries

pkg/registry/common/dial/ns_client.go, pkg/registry/common/dial/nse_client.go
|refresh count|memory kB|
| ------------ | ------ |
1|6000
10|8000
100|**22000**
500|**80000**
1000| **FAIL**
|refresh count|memory kB|
| ------------ | ------ |
1|6000
10|8000
100|**9000**
500|**10000**
1000|**10000**
=> fix: stop resource leaking in client connections on find queries

pkg/networkservice/common/begin/merge.go, pkg/networkservice/common/begin/rerequest_client_test.go
Also improved greatly documentation in various places
Should resolve https://github.com/networkservicemesh/sdk/pull/1234
=> Improve merge of ConnectionContext with external requests

pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/common/discover/match_selector.go
Temporarily delete label-matching for NSEs. CI fails because of this (https://github.com/networkservicemesh/integration-k8s-kind/pull/605). Label-matching will be reworked in this issue: https://github.com/networkservicemesh/sdk/issues/1239
https://github.com/networkservicemesh/sdk/issues/1239
=> Delete label matching

pkg/networkservice/common/cleanup/cleanup_test.go, pkg/networkservice/common/cleanup/client.go, pkg/networkservice/common/cleanup/doc.go, pkg/networkservice/common/cleanup/metadata.go, pkg/networkservice/common/cleanup/options.go, staticcheck.conf
This PR adds new chain element that cleans up resources on `chainCtx.Done()`
Issue: https://github.com/networkservicemesh/sdk-vpp/issues/516
=> Add cleanup chain element

pkg/tools/spire/server.conf.go, pkg/tools/spire/start.go
Spire `v1.2.2` has different configuration. The main update: `registrationUDSPath` was removed.
https://github.com/networkservicemesh/deployments-k8s/issues/5379
=> Update configuration to be consistent with spire v1.2.2

pkg/registry/common/dial/ns_client.go, pkg/registry/common/dial/nse_client.go
Reported by  @damiankopyto in the nsm slack
We face with this on the real production cluster
```go
Apr 20 19:40:35.817[37m [TRAC] [type:registry] [0m(5.1)       find={"network_service":{"name":"nse-composition","payload":"ETHERNET"}}
Apr 20 19:40:35.992[31m [ERRO] [type:registry] [0m(5.2)       can not dial to registry:5002, err failed to dial registry:5002: context deadline exceeded. Deleting clientconn...
Apr 20 19:40:35.994[31m [ERRO] [type:registry] [0m(5.3)       failed to dial registry:5002: context deadline exceeded
Apr 20 19:40:35.994[31m [ERRO] [type:registry] [0m(4.2)      failed to dial registry:5002: context deadline exceeded
Apr 20 19:40:35.994[31m [ERRO] [type:registry] [0m(3.2)     failed to dial …
```
=> fix: default registry dial timeout could be not enough for some clusters

pkg/tools/log/logger.go
> Error prints can still be seen in the logs after deploying the basic kernel2kernel example from the repo:
```
Apr 21 11:31:46.821 [ERRO] [type:registry] (7.3)         failed to dial unix:///var/lib/networkservicemesh/nsm.io.sock: context deadline exceeded
Apr 21 11:31:46.821 [ERRO] [type:registry] (6.2)        failed to dial unix:///var/lib/networkservicemesh/nsm.io.sock: context deadline exceeded
Apr 21 11:31:46.821 [ERRO] [type:registry] (5.3)       failed to dial unix:///var/lib/networkservicemesh/nsm.io.sock: context deadline exceeded
Apr 21 11:31:46.821 [ERRO] [type:registry] (4.2)      failed to dial unix:///var/lib/networkservicemesh/nsm.io.sock: context deadline exceeded
Apr 21 11:31:46.821 [ERRO] [type:registry] (3.2) …
```
=> fix: enable trace logging only if logrus.LogLevel() is TRACE

pkg/tools/spire/agent.conf.go, pkg/tools/spire/options.go, pkg/tools/spire/server.conf.go, pkg/tools/spire/start.go
With this PR we can customize the spire configuration.
Main things that have been added:
- Federation field
- Agent configuration option
- Server configuration option
- Slightly simplified the default configuration - spire has default values ​​in the latest version
https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/issues/1
=> Make local spire more configurable

pkg/networkservice/chains/nsmgrproxy/server_test.go, pkg/networkservice/common/interdomainbypass/server.go
This PR fixes problem with translating interdomain queries from the remote site to the local. 
It is also fixes  vl3 + interdomain cases, because we are selecing fib table based on the service name. 
As an additional benifit it also removes extra registry lookup for the inter-domain network service resolve
=> qfix: remove extra registry lookup for the inter-domain network service resolve

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/registry/chains/client/ns_client.go, pkg/registry/chains/client/nse_client.go, pkg/registry/chains/client/option.go, pkg/registry/common/dnsresolve/ns_client.go, pkg/registry/common/dnsresolve/ns_server.go, pkg/registry/common/dnsresolve/nse_client.go, pkg/registry/common/heal/find_test.go, pkg/registry/common/retry/ns_client.go, pkg/tools/sandbox/node.go, pkg/tools/sandbox/types.go
We need to resolve dns for a docker container. Therefore, in addition to Server elements, we also need Client elements.
https://github.com/networkservicemesh/cmd-nse-simple-vl3-docker/issues/1
=> Add dnsresolve client chain elements

pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go
Fixes the problem when client is triying to fanout DNS to itself and falling to the loop! 
Scenarious:
Scenario 1:
1. nsc POD restarted
Expected: we dont lost resolv.conf entries
Scenario 1:
1. nsc-init started
2. nsc-init-done
3. nsc started
Expected: we dont lost resolv.conf entries
https://github.com/networkservicemesh/cmd-nse-istio-proxy/issues/4
=> qfix:  restore default resolv.conf file on application restarting/stopping

pkg/networkservice/connectioncontext/externaldnscontext/server.go, pkg/networkservice/connectioncontext/externaldnscontext/server_test.go
This PR simply adds networkservice `externaldnscontext` chain elements that gets dnsconfigs from the remote side (floating dns service).
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/45
=> feat: add externaldnscontext networkservice chain element

pkg/networkservice/ipam/singlepointipam/server.go, pkg/networkservice/ipam/singlepointipam/server_test.go
Do not set dst in IP context  in case of singlepoint IPAM
networkservicemesh/cmd-nsc#447
=> Data path healing should be disabled

pkg/networkservice/common/metrics/metadata.go, pkg/networkservice/common/metrics/server.go, pkg/networkservice/common/metrics/server_test.go
The metrics map should be unique for each connection and shouldn't cause concurrency issues.
In this PR the map has been moved from the chain element to the metadata.
Closes: https://github.com/networkservicemesh/sdk/issues/1311
=> Fix metrics concurrency

pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go
Endpoint appends its DNS configs to configs which are already in the connection on first request from a client. Client saves these DNS configs. On Refresh client sends request with saved configs to the endpoint and the endpoint appends its configs again. It leads to duplication of the endpoint's dns configs on refreshes.
=> Always add initial client DNS config to request

pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go, pkg/networkservice/connectioncontext/dnscontext/server.go
=> Remove duplicate dns configs in response connection in DNSContextClient

pkg/networkservice/common/monitor/eventloop.go, pkg/networkservice/common/monitor/metadata.go, pkg/networkservice/common/monitor/monitor_connection_server.go, pkg/networkservice/common/monitor/server.go, pkg/networkservice/connectioncontext/mtu/vl3mtu/client.go, pkg/networkservice/connectioncontext/mtu/vl3mtu/client_test.go, pkg/networkservice/connectioncontext/mtu/vl3mtu/doc.go, pkg/networkservice/connectioncontext/mtu/vl3mtu/server.go, pkg/networkservice/connectioncontext/mtu/vl3mtu/server_test.go
This PR provides chain elements to store the minimum value of vl3 MTU and send monitor events with a REFRESH_REQUESTED state if that value has changed.
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/77
=> Add vl3mtu chain element

pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/clusterinfo/options.go, pkg/networkservice/common/clusterinfo/server.go, pkg/networkservice/common/clusterinfo/server_test.go, pkg/registry/common/clusterinfo/nse_server.go, pkg/registry/common/clusterinfo/nse_server_test.go, pkg/registry/common/clusterinfo/options.go
https://github.com/networkservicemesh/cmd-cluster-info-k8s/issues/1
=> feat: add cluster-info chain elements

pkg/networkservice/connectioncontext/dnscontext/server.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go, pkg/tools/dnsutils/dnsutils.go
1. The main fix is `GetSrcIPRoutes` -> `GetSrcRoutes`
2. Prevented dnsContext duplication
3. Other changes because of linter `cyclomatic complexity`
https://github.com/networkservicemesh/deployments-k8s/issues/6774
=> Fixes for vl3_dns

pkg/tools/dnsutils/cache/handler.go, pkg/tools/dnsutils/fanout/handler.go
If we run `dig` or `nslookup` with `norec` flag, these commands may return a positive result (`NOERROR`) but without `Answer` section. We must handle this situation.
Closes: https://github.com/networkservicemesh/integration-k8s-packet/issues/294
=> Handle empty dns answer

pkg/tools/dnsutils/dnsutils.go, pkg/tools/dnsutils/memory/handler.go
Main changes:
1. Increase default dns timeout to 5 sec. It is linux default value - https://man7.org/linux/man-pages/man5/resolv.conf.5.html
2. `memory` dns has to write something into the writer (even if the entry is not found)
https://github.com/networkservicemesh/integration-k8s-packet/issues/295
=> Increase DNS timeout

pkg/tools/cidr/group.go, pkg/tools/cidr/group_test.go
This PR allows us to combine CIDRs into groups (see [link](https://github.com/networkservicemesh/deployments-k8s/issues/7051#issuecomment-1212823093))
https://github.com/networkservicemesh/deployments-k8s/issues/7051#issuecomment-1212823093
=> Add cidr groups support

pkg/registry/core/trace/ns_registry.go, pkg/registry/core/trace/nse_registry.go
We were getting a *lot* of log chaff at TRACE level during normal operation because gRPC returns a "context canceled" error periodically but it's not really an error for us because we immediately loop around again.
This commit uses the gRPC status.Code() method to identify these non-errors. It also uses errors.Is() instead of == to compare error objects. This handles wrapped errors.
https://pkg.go.dev/google.golang.org/grpc/status#Code
https://github.com/golang/go/wiki/ErrorValueFAQ#how-should-i-change-my-error-handling-code-to-work-with-the-new-features
https://github.com/networkservicemesh/sdk/issues/1068
Deploy cmd-nse-icmp-responder, see periodic "context cancelled" errors, deploy build with patched SDK, verify that errors aren't present.
Only relevant when running at TRACE log level.
=> Don't trace gRPC "Canceled" errors

pkg/registry/chains/memory/server.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
=> Add OPA to registry-memory server

pkg/networkservice/chains/nsmgrproxy/server.go
=> Add options with OPA policies to nsmgr-proxy

pkg/networkservice/common/begin/client.go, pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/begin/event_factory_client_test.go, pkg/networkservice/common/begin/event_factory_server_test.go, pkg/networkservice/common/begin/server.go, pkg/registry/common/begin/ns_client.go, pkg/registry/common/begin/ns_server.go, pkg/registry/common/begin/nse_client.go, pkg/registry/common/begin/nse_event_factory_client_test.go, pkg/registry/common/begin/nse_event_factory_server_test.go, pkg/registry/common/begin/nse_server.go
Don't restore eventFactory in case the connection has already been closed/unregistered (it was removed from the map)
We ran into this when we started using values ​​from the passed context (for example spiffeID)
=> Don't restore eventFactory after Close/Unregister

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/common/heal/eventloop.go
https://github.com/networkservicemesh/sdk/issues/1359
=> heal: fix dataplane healing

pkg/networkservice/common/begin/client.go, pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/begin/event_factory_client_test.go, pkg/networkservice/common/begin/event_factory_server_test.go, pkg/networkservice/common/begin/server.go, pkg/registry/common/begin/ns_client.go, pkg/registry/common/begin/ns_event_factory.go, pkg/registry/common/begin/ns_server.go, pkg/registry/common/begin/nse_client.go, pkg/registry/common/begin/nse_event_factory.go, pkg/registry/common/begin/nse_event_factory_client_test.go, pkg/registry/common/begin/nse_event_factory_server_test.go, pkg/registry/common/begin/nse_server.go
Steps to reproduce:
1. Deploy any NSM remote case (for example kernel2vxlan2kernel)
2. Delete remote Nsmgr pod
3. Wait for a new Nsmgr
4. Delete NSE pod
See - `network service endpoint {NAME} not found: all forwarders have failed`
After restarting the remote Nsmgr, it reconnects to the remote Forwarder with the same `connID`, but with a **_different context values_** (this is needed for `authorize` chain element). 
`begin` has a map that stores the eventFactory by `connID`. When the recreated Nsmgr reaches the Forwarder, we use the previous eventFactory with the **_old internal context_**.
After that, all calls from `eventFactory` will fail. For example, [nsmonitor](https://github.com/networkservicemesh/sdk-vpp/tree/main/pkg/networ …
=> Fix begin on refresh

pkg/networkservice/common/excludedprefixes/client.go, pkg/networkservice/common/excludedprefixes/client_test.go
We shouldn't exclude whole subnets on refresh
=> qfix: Dont exclude subnets from routes

pkg/networkservice/common/begin/client.go, pkg/networkservice/common/begin/event_factory_client_test.go, pkg/networkservice/common/begin/event_factory_server_test.go, pkg/networkservice/common/begin/server.go, pkg/registry/common/begin/ns_client.go, pkg/registry/common/begin/ns_server.go, pkg/registry/common/begin/nse_client.go, pkg/registry/common/begin/nse_event_factory_client_test.go, pkg/registry/common/begin/nse_event_factory_server_test.go, pkg/registry/common/begin/nse_server.go
We should update the eventFactory context **only after** successful refresh.
**The reason**: we update eventFactory request only if we don't have an error - https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/begin/server.go#L75-L77
Thus, if we update the context before the request and it fails, we will have the wrong state (new context but previous request)
https://github.com/networkservicemesh/sdk/issues/1357
=> begin: update context after a successful request

pkg/tools/log/defaultlogger.go, pkg/tools/log/logger.go, pkg/tools/log/logruslogger/logruslogger.go
It should be possible to set an own customizwd Logger to be used by NSM. Now the logger is hard-coded in some places, most notable the `logruslogger.FromSpan()` used for trace logging. The intention for this PR is to fix the most urgent needs in a backward compatible way with as little changes as possible.
This PR adds a global logger reachable with `log.L()` (same as [zap](https://github.com/uber-go/zap)) and settable with `log.SetGlobalLogger(l Logger)`.
`logruslogger.FromSpan()` has been altered to become generic by using the `log.Logger` interface rather than a variation of `logruslogger`. It uses the global logger as base (calls `log.L()`) and thus allows users to specify the logger used for trace. ~For backward compatibility the global Logger is set to a `logruslogger` on init.~ If …
=> Settable global logger

pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go, pkg/tools/dnsutils/memory/handler.go, pkg/tools/dnsutils/memory/handler_test.go
`ip.To16() != nil` doesn't mean that this is IPv6 address - https://github.com/golang/go/blob/master/src/net/ip.go#L226-L234
It can convert IPv4 to IPv6.
We can only rely on `ip.To4()`
https://github.com/networkservicemesh/integration-k8s-aws/issues/322
=> Fix ipv6 dns entries

pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_test.go
https://github.com/networkservicemesh/deployments-k8s/issues/7792
=> Fix empty map panic in networkservice authorize.Close

pkg/networkservice/common/prioritymechanisms/client.go, pkg/networkservice/common/prioritymechanisms/client_test.go
This PR adds `priorityMechanisms` chain element.
The input is a list of mechanisms by priority. On the Request, the chain element sorts the mechanism preferences according to these priorities.
This element will be used on the forwarder.
https://github.com/networkservicemesh/sdk-vpp/issues/638
=> Add priorityMechanisms chain element

pkg/networkservice/common/mechanismpriority/client.go, pkg/networkservice/common/mechanismpriority/client_test.go
https://github.com/networkservicemesh/sdk-vpp/issues/638
=> Rename prioritymechanisms to mechanismpriority

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/registry/chains/memory/server.go, pkg/registry/chains/proxydns/server.go
Begin doesn't get updated path in Context when we call Register or Unregister using eventFactory
=> [qfix] Swap begin and updatepath chain elements in all registries

pkg/tools/dnsutils/dnsconfigs/handler.go, pkg/tools/dnsutils/dnsconfigs/handler_test.go, pkg/tools/dnsutils/dnsconfigs/response_writer.go, pkg/tools/dnsutils/dnsconfigs/tcp_dns_server_test.go, pkg/tools/dnsutils/searches/handler.go
https://github.com/networkservicemesh/deployments-k8s/issues/7694
=> Separate UDP and TCP queries for DNS Server

pkg/networkservice/common/begin/client.go, pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/begin/event_factory_client_test.go, pkg/networkservice/common/begin/event_factory_server_test.go, pkg/networkservice/common/begin/server.go, pkg/registry/common/begin/ns_client.go, pkg/registry/common/begin/ns_event_factory.go, pkg/registry/common/begin/ns_server.go, pkg/registry/common/begin/nse_client.go, pkg/registry/common/begin/nse_event_factory.go, pkg/registry/common/begin/nse_event_factory_client_test.go, pkg/registry/common/begin/nse_event_factory_server_test.go, pkg/registry/common/begin/nse_server.go
In the current implementation, we update the `eventFactory` context [after a successful request](https://github.com/networkservicemesh/sdk/blob/main/pkg/networkservice/common/begin/client.go#L85).
This is not quite right, because in addition to updating the context values, we also update **_the request timeout_**. It is calculated on the wayback.
For example, the request came with a timeout of 15s and took 5s. For the event factory, we calculate 10s, but we need 15s.
=> begin: update eventFactory context based on the initial one

pkg/tools/dnsutils/fanout/handler.go
https://github.com/networkservicemesh/integration-k8s-aws/issues/324
=> dns fanout: wrap IPv6 address

pkg/registry/common/authorize/ns_client.go, pkg/registry/common/authorize/ns_server.go, pkg/registry/common/authorize/nse_client.go, pkg/registry/common/authorize/nse_server.go, pkg/registry/common/authorize/options.go, pkg/registry/common/grpcmetadata/common.go, pkg/registry/common/grpcmetadata/ns_client.go, pkg/registry/common/grpcmetadata/ns_server.go, pkg/registry/common/grpcmetadata/ns_test.go, pkg/registry/common/grpcmetadata/nse_client.go, pkg/registry/common/grpcmetadata/nse_server.go, pkg/registry/common/grpcmetadata/nse_test.go
We can make a private path from grpcmetadata optional. 
If registry auth is enabled then OPA will fail registers/unregisters by default policies for any combinations of old/new components.
If registry auth is disabled then the private path could be invalid, but old NSM could work with any combination of old/new components.
https://github.com/networkservicemesh/deployments-k8s/issues/8187
=> fix: Return backward compatibility

pkg/registry/common/authorize/common.go, pkg/registry/common/authorize/ns_client.go, pkg/registry/common/authorize/ns_server.go, pkg/registry/common/authorize/nse_client.go, pkg/registry/common/authorize/nse_server.go
getSpiffeIDFromPath should return empty spiffeID from empty path. For backward compatibility.
=> [qfix] Return empty spiffeID if path is empty

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/networkservice/chains/nsmgrproxy/server.go, pkg/networkservice/common/timeout/server.go, pkg/registry/chains/memory/server.go, pkg/registry/chains/proxydns/server.go, pkg/registry/common/authorize/ns_client.go, pkg/registry/common/authorize/nse_client.go, pkg/registry/common/begin/ns_client.go, pkg/registry/common/begin/ns_server.go, pkg/registry/common/begin/nse_client.go, pkg/registry/common/begin/nse_server.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/grpcmetadata/common_test.go, pkg/registry/common/grpcmetadata/ns_client.go, pkg/registry/common/grpcmetadata/ns_test.go, pkg/registry/common/grpcmetadata/nse_client.go, pkg/registry/common/grpcmetadata/nse_test.go, pkg/registry/common/updatepath/ns_server_test.go, pkg/registry/common/updatepath/nse_server.go, pkg/registry/common/updatepath/nse_server_test.go, pkg/registry/utils/inject/injectpeertoken/ns_server.go, pkg/registry/utils/inject/injectpeertoken/nse_server.go, pkg/tools/opa/policies/common/tokens_expired.rego, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
Main changes:
1. **networkservice timeout**: at the time of the call `Close()` on `timeout`, the token may already be expired. Therefore, we need to call `Close()` in advance - `(tokenTimeout - requestTimeout)`
2. **registry expire**:  since we now have tokens in the registry, we must follow the same logic as in the **networkservice** (see above). Expiration time selection has been extended. Now it is  - `min(peertoken.ExpirationTime, token.ExpirationTime, nse.ExpirationTIme) - registerTimeout`.
3. **grpcmetadata.NewNetworkServiceEndpointRegistryClient** - `grpc.Header` was added to `Unregister()` to process an updated `path` on the way back (like here - https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/grpcme …
=> Fix timeout/expire chain elements

pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/single_test.go, pkg/registry/chains/memory/server.go, pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/expire/options.go, pkg/tools/sandbox/builder.go, pkg/tools/sandbox/types.go
`WithDefaultExpiration` sets default expiration time for endpoint if it was not set before
https://github.com/networkservicemesh/sdk/issues/1398
=> Add default expiration option for registry

pkg/networkservice/ipam/groupipam/server.go, pkg/networkservice/ipam/groupipam/server_test.go
Reduces code for nses. 
For example, these lines could be removed with this patch
1. https://github.com/networkservicemesh/cmd-nse-icmp-responder/blob/main/main.go#L409-L415
2. https://github.com/networkservicemesh/cmd-nse-icmp-responder-vpp/blob/main/main.go#L328-L334
3. https://github.com/networkservicemesh/cmd-nse-remote-vlan/blob/main/main.go#L318-L329
=> feat: add groupipam networkservice server chain element

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/common/monitor/monitor_connection_server.go, pkg/networkservice/connectioncontext/dnscontext/resolvconf.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go
Issue: https://github.com/networkservicemesh/integration-k8s-kind/issues/750
Closes: https://github.com/networkservicemesh/sdk/pull/1392
=> [vl3-dns]: send REFRESH_REQUESTED event if dnsServerAddress was changed

pkg/tools/dnsutils/searches/handler.go, pkg/tools/dnsutils/searches/handler_test.go, pkg/tools/dnsutils/searches/response_writer.go
From `man resolv.conf` :
> **search** Search list for host-name lookup.
> ...
> Resolver queries ... will be attempted  using  each  component  of  the search  path  **in  turn** until a match is found
It will be much more efficient if we check the success of the dns request one by one, rather than all at once.
https://github.com/networkservicemesh/sdk/issues/1414
=> Fix searches dns chain element

pkg/ipam/vl3ipam/server.go, pkg/ipam/vl3ipam/server_test.go
https://github.com/networkservicemesh/integration-k8s-kind/issues/776
=> Add logs to vl3-ipam server

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/common/monitor/monitor_connection_server.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go, pkg/tools/dnsutils/dnsutils.go
This PR partially reverts this - https://github.com/networkservicemesh/sdk/pull/1416
The previous approach using `monitor` and sending `REFRESH_REQUESTED` event is not suitable, since there is some time (even if very little) between the `Request` and `MonitorConnections`. Because of this, we get into a situation where both the `Request` and the event may not update the DNS context.
In this PR we return an error until the address is assigned. **_But_** we must allow Request to itself, because that Request is what selects the addresses.
https://github.com/networkservicemesh/integration-k8s-kind/issues/750
=> Return an error if there is no DNS address.

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go
=> Fix vl3 dns

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/options.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go
Interdomain template functions have been added to `vl3dns`. 
Now we can use a DNS template like this:
`{{ index .Labels \“podName\” }}.{{ target .NetworkService }}.{{ domain .NetworkService }}.`
https://github.com/networkservicemesh/sdk/issues/1414
=> Add interdomain funcs to vl3-dns template

pkg/networkservice/ipam/singlepointipam/README.md, pkg/networkservice/ipam/singlepointipam/server.go, pkg/networkservice/ipam/singlepointipam/server_test.go
Single-point IPAM should not allocate broadcast address
Remote vlan nse is used to provide cluster breakout. The assigned IP to the front-end NSC can not be broadcast address.
#1430
=> remote-vlan-nse fix; Singlepoint IPAM should not allocate broadcast address

pkg/tools/dnsutils/memory/handler.go, pkg/tools/dnsutils/memory/handler_test.go
[](https://github.com/networkservicemesh/sdk/issues/1442)
=> Rework request handling in memory handler

pkg/networkservice/common/authorize/common.go, pkg/registry/common/authorize/common.go, pkg/tools/monitorconnection/authorize/common.go, pkg/tools/monitorconnection/authorize/server_test.go, pkg/tools/opa/policies.go, pkg/tools/opa/policy.go
Add more logs to policies checking.
Error output:
```
2023/04/18 14:28:47 [ERROR] policy failed: policy.rego
```
Incident: https://github.com/networkservicemesh/integration-k8s-kind/actions/runs/4665104418/jobs/8258077225
Logs (no information about failed policy):
```
...
Apr 11 08:21:05.750[31m [ERRO] [id:alpine-74dcb6dd55-kfx57-0] [type:networkService] [0m(8.3)          an error occurred during authorization policy check: rpc error: code = PermissionDenied desc = no sufficient privileges
Apr 11 08:21:05.750[31m [ERRO] [id:alpine-74dcb6dd55-kfx57-0] [type:networkService] [0m(7.1)         an error occurred during authorization policy check: rpc error: code = PermissionDenied desc = no sufficient privileges
...
```
=> [qfix] Add more logs to policies checking

pkg/networkservice/core/trace/client.go, pkg/networkservice/core/trace/common.go, pkg/networkservice/core/trace/context.go, pkg/networkservice/core/trace/server.go, pkg/registry/core/trace/common.go, pkg/registry/core/trace/context.go, pkg/registry/core/trace/ns_registry.go, pkg/registry/core/trace/nse_registry.go, pkg/tools/dnsutils/trace/context.go, pkg/tools/dnsutils/trace/handler.go, pkg/tools/log/common.go, pkg/tools/log/logruslogger/logruslogger.go, pkg/tools/log/spanlogger/span.go, pkg/tools/log/spanlogger/spanlogger.go, pkg/tools/opentelemetry/opentelemetry.go
Fixes:
1. Added `opentelemetry` `TextMapPropagator` to link spans of different applications
2. Added human-readable root span title
3. Refreshes are displayed in separate spans
Jaeger output example (from the client):
https://github.com/networkservicemesh/sdk/issues/1441
=> Opentelemetry fixes

pkg/networkservice/chains/nsmgr/select_forwarder_test.go, pkg/networkservice/common/discoverforwarder/server.go
Closes https://github.com/networkservicemesh/integration-k8s-kind/pull/813
https://github.com/networkservicemesh/integration-k8s-kind/pull/813
=> qfix: Simplify forwarder selection

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/connectioncontext/dnscontext/client.go, pkg/networkservice/connectioncontext/dnscontext/client_test.go, pkg/networkservice/connectioncontext/dnscontext/vl3dns/server.go
Main changes:
1. NSC shouldn't add private resolv.conf fields to `Request` in `dnsContextClient`
2. vl3-dns should add search domains for the Connection. If DNS record is `"target.d1.d2.d3."` - it adds `["d1.d2.d3", "d2.d3", "d3"]`
https://github.com/networkservicemesh/sdk/issues/1426
=> Fix vl3 dns configurations

pkg/tools/spire/server.conf.go
Removed `default_svid_ttl` configuration parameter since it was renamed in SPIRE 1.6 and the default value (`1h`) is used anyway. This change enables to update the `Dockerfiles` (see below) gradually with the new SPIRE version, no need to change all of them at once, because the default value is the same for both versions however the name of the configurable changed.
```
ADD https://github.com/spiffe/spire/releases/download/v1.6.1/spire-1.6.1-linux-x86_64-glibc.tar.gz .
RUN tar xzvf spire-1.6.1-linux-x86_64-glibc.tar.gz -C /bin --strip=2 spire-1.6.1/bin/spire-server spire-1.6.1/bin/spire-agent
```
Connected to [#8963](https://github.com/networkservicemesh/deployments-k8s/pull/8963).
=> default_svid_ttl config removed

pkg/registry/chains/client/ns_client.go, pkg/registry/chains/client/nse_client.go, pkg/registry/chains/memory/server.go, pkg/registry/common/setregistrationtime/metadata.go, pkg/registry/common/setregistrationtime/nse_server.go, pkg/registry/common/setregistrationtime/nse_server_test.go, pkg/registry/utils/inject/injecterror/ns_server.go, pkg/registry/utils/metadata/context.go, pkg/registry/utils/metadata/doc.go, pkg/registry/utils/metadata/ns_client.go, pkg/registry/utils/metadata/ns_server.go, pkg/registry/utils/metadata/ns_test.go, pkg/registry/utils/metadata/nse_client.go, pkg/registry/utils/metadata/nse_server.go, pkg/registry/utils/metadata/nse_test.go
We should not change the `InitialRegistrationTime` field if we have already registered the NSE before.
Added registry `metadata` chain element
https://github.com/networkservicemesh/deployments-k8s/issues/9063
=> Fix InitialRegistrationTime in case of reregistration

pkg/networkservice/core/trace/context.go, pkg/registry/common/authorize/common.go, pkg/registry/core/trace/common.go, pkg/registry/core/trace/context.go, pkg/tools/dnsutils/trace/context.go, pkg/tools/log/logger.go, pkg/tools/log/logruslogger/logruslogger.go
This is continuation of - https://github.com/networkservicemesh/sdk/pull/1475
(see description there)
<details>
<summary>Example logs from forwarder with `DEBUG` log level</summary>
```log
Jul 13 07:15:46.402 [INFO] [cmd:/bin/forwarder] Setting env variable DLV_LISTEN_FORWARDER to a valid dlv '--listen' value will cause the dlv debugger to execute this binary and listen as directed.
Jul 13 07:15:46.402 [INFO] [cmd:/bin/forwarder] there are 9 phases which will be executed followed by a success message:
Jul 13 07:15:46.402 [INFO] [cmd:/bin/forwarder] the phases include:
Jul 13 07:15:46.402 [INFO] [cmd:/bin/forwarder] 1: get config from environment
Jul 13 07:15:46.402 [INFO] [cmd:/bin/forwarder] 2: run vpp and get a connection to it
Jul 13 07:15:46.402 [INFO] [cmd:/bin/forwarder] 3: get …
```
=> (continuation) Enable logs from chain elements regardless of EnableTracing

.golangci.yml, pkg/networkservice/common/mechanisms/kernel/vlan/server.go, pkg/networkservice/common/mechanisms/server_test.go, pkg/networkservice/common/timeout/server.go, pkg/networkservice/connectioncontext/ipcontext/vl3/client.go, pkg/networkservice/connectioncontext/ipcontext/vl3/server.go, pkg/networkservice/core/adapters/networkservice_test.go, pkg/registry/common/dnsresolve/ns_server.go, pkg/tools/grpcutils/errors.go, pkg/tools/sandbox/fake_resolver.go
=> [qfix] Enable depguard linter

pkg/networkservice/connectioncontext/mtu/vl3mtu/server.go, pkg/networkservice/connectioncontext/mtu/vl3mtu/server_test.go
https://github.com/networkservicemesh/deployments-k8s/issues/9210
=> [qfix] vl3mtu: store cloned conn

pkg/networkservice/chains/nsmgr/dns_test.go, pkg/networkservice/chains/nsmgr/server.go, pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/chains/nsmgr/utils_test.go, pkg/networkservice/common/discover/match_selector.go, pkg/networkservice/common/discover/server.go, pkg/networkservice/common/netsvcmonitor/metadata.go, pkg/networkservice/common/netsvcmonitor/server.go, pkg/tools/matchutils/utils.go
Fixes https://github.com/networkservicemesh/deployments-k8s/issues/9767
https://github.com/networkservicemesh/deployments-k8s/issues/9767
=> feat: add netsvcmonitor chain element

pkg/networkservice/common/discover/server_test.go, pkg/tools/matchutils/utils.go
do not choose endpoints that doesn't match with the network service
=> fix: do not choose endpoints that doesn't match the network service

pkg/networkservice/common/netsvcmonitor/server.go, pkg/networkservice/common/netsvcmonitor/server_test.go
Currenly, we're not support adanced query parameters https://github.com/networkservicemesh/api/issues/51 and for now Find queries could return similar network services
https://github.com/networkservicemesh/sdk/issues/1521
=> fix: Skip similar networkservices in netsvcmonitor element

pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/begin/event_factory_client_test.go
Chain elements in Closes can rely on the context and its timeout. Therefore, after the operation is completed, the context must be canceled.
=> [begin]: event_factory should cancel Close context in case of reselect

pkg/networkservice/common/netsvcmonitor/server.go, pkg/registry/common/connect/ns_server_test.go, pkg/registry/common/connect/nse_server_test.go, pkg/registry/common/memory/ns_server_test.go, pkg/registry/common/memory/nse_server_test.go, pkg/tools/matchutils/utils.go, pkg/tools/matchutils/utils_test.go
Related to discussion about https://github.com/networkservicemesh/sdk/issues/1521 from WG call
=> qfix: Use strict name comparison for nse/ns servers

pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/common/begin/event_factory.go
Closes https://github.com/networkservicemesh/deployments-k8s/issues/9888
=> fix: Do not use settings from the previous connection if the connection was reselected

pkg/networkservice/common/authorize/client.go, pkg/networkservice/common/authorize/client_test.go, pkg/networkservice/common/authorize/metadata.go, pkg/registry/common/authorize/ns_client.go, pkg/registry/common/authorize/ns_client_test.go, pkg/registry/common/authorize/nse_client.go, pkg/registry/common/authorize/nse_client_test.go, pkg/tools/opa/opainput.go, pkg/tools/spiffejwt/token.go
The main idea is not to close the existing connection during refresh in case of an error.
This corrects the situation where the spire certificate update occurred during the Request. This may return a false negative result
https://github.com/networkservicemesh/deployments-k8s/issues/10377
=> Fix authorizeClient on failed refresh

pkg/networkservice/common/discoverforwarder/server.go, pkg/networkservice/ipam/groupipam/server_test.go, pkg/networkservice/ipam/point2pointipam/server.go, pkg/networkservice/ipam/point2pointipam/server_test.go
Related to https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/664
=> fix: Correctly handle RESELECT_REQUESTED state and clearing point2pointipam

pkg/registry/common/clientconn/nse_client.go, pkg/registry/common/localbypass/server.go
Some fixes to let NSE Unregister itself without issues
https://github.com/networkservicemesh/integration-k8s-kind/pull/936
=> [qfix] Some minor fixes for NSE Unregister scenario

pkg/networkservice/common/heal/client_filter.go, pkg/networkservice/common/monitor/client_filter.go, pkg/networkservice/common/monitor/server_test.go
Closes: https://github.com/networkservicemesh/sdk/issues/1569
=> Handle INITIAL_STATE_TRANSFER only if connection state was changed

pkg/registry/common/begin/nse_event_factory.go, pkg/tools/extend/extended.go
Fixes this comment: https://github.com/networkservicemesh/sdk/pull/1533#pullrequestreview-1724706085
=> [qfix] Use clearer function name in `extend` package

.github/workflows/ci.yaml, pkg/networkservice/common/mechanisms/recvfd/server_test.go
https://github.com/networkservicemesh/sdk/issues/1525
=> Fix TestRecvfdClosesSingleFile

pkg/networkservice/chains/nsmgr/suite_test.go, pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/ipam/strictipam/server.go
As we'd discussed on the latest meeting, we decided not to clear the IP context on the NSC side.  See at https://github.com/networkservicemesh/deployments-k8s/issues/9888#issuecomment-1906520918
Closes  https://github.com/networkservicemesh/deployments-k8s/issues/9888
=> qfix: Do not reset IPContext configuration on the reselect

pkg/networkservice/core/trace/traceconcise/common_test.go, pkg/networkservice/core/trace/traceverbose/common_test.go, pkg/registry/core/trace/traceconcise/traceconcise_test.go, pkg/tools/log/logruslogger/formatter.go
Introduced an option to disable the coloring of the log messages and thus remove the control characters responsible for it, via an optionally defined environmental variable.
https://github.com/networkservicemesh/sdk/issues/1594
=> Disable log coloring

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/client_test.go, pkg/networkservice/common/mechanisms/kernel/option.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/kernel/server_test.go, pkg/networkservice/common/mechanisms/kernel/utils.go, pkg/networkservice/common/mechanisms/kernel/utils_test.go, pkg/networkservice/common/mechanismtranslation/client_test.go, pkg/tools/nanoid/generator.go, pkg/tools/nanoid/generator_test.go
Generate random kernel interface names of a form `nsm############` where `#` is a random character.
https://github.com/networkservicemesh/sdk/issues/1589
=> Generate random kernel interface names

pkg/networkservice/chains/nsmgr/server.go, pkg/registry/chains/client/ns_client.go, pkg/registry/chains/client/nse_client.go, pkg/registry/chains/client/option.go
Several options were missed
https://github.com/networkservicemesh/deployments-k8s/issues/11372
=> Pass dial timeout as option

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/connectioncontext/ipcontext/vl3/client.go, pkg/networkservice/connectioncontext/ipcontext/vl3/client_test.go, pkg/networkservice/connectioncontext/ipcontext/vl3/ipam.go, pkg/networkservice/connectioncontext/ipcontext/vl3/ipam_test.go, pkg/networkservice/connectioncontext/ipcontext/vl3/server_test.go
https://github.com/networkservicemesh/cmd-nse-vl3-vpp/issues/289
=> Add a constructor for vl3.IPAM

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/connectioncontext/ipcontext/vl3/ipam.go
=> Fix vl3 ipam refresh

pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/kernel/server_test.go
We need to generate the interface name only if the mechanism doesn't have one.
=> Fix kernel interface name generation

pkg/registry/common/expire/nse_server.go, pkg/registry/common/expire/nse_server_test.go, pkg/registry/common/updatepath/context.go, pkg/registry/common/updatepath/nse_server.go, pkg/tools/token/context.go
Expiration logic should be in the expire chain element
=> Move registry expiration handling from updatepath to expire

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/client_test.go, pkg/networkservice/common/mechanisms/kernel/option.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/kernel/server_test.go, pkg/networkservice/common/mechanisms/kernel/utils.go, pkg/tools/nanoid/utils.go
https://github.com/networkservicemesh/integration-k8s-gke/issues/435
=> Make the kernel generateInterfaceName function public

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/tools/nanoid/generator.go, pkg/tools/nanoid/generator_test.go, pkg/tools/nanoid/utils.go
=> Refactor nanoid package

.github/workflows/update-dependent-repositories-gomod.yaml
https://github.com/networkservicemesh/.github/issues/67
=> Remove `automerge is completed` trigger from Update dependent repositories workflow

pkg/networkservice/common/mechanisms/recvfd/client.go, pkg/networkservice/common/mechanisms/recvfd/server.go, pkg/registry/common/recvfd/client.go, pkg/registry/common/recvfd/server.go
In case the request or registration was not successful, the FD leak. 
This PR fixes the problem.
Closes https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/1025
Closes https://github.com/networkservicemesh/cmd-nsmgr/issues/675
=> Fix fd mem leaks in nsmgr and forwarder

pkg/tools/opa/policy.go
OPA policies may cache some parameters when compiled. This PR makes them compile again with new values every time they are called
https://github.com/networkservicemesh/sdk/issues/1622
=> Fix some leaks in opa policies

pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/mechanisms/recvfd/server_test.go, pkg/networkservice/utils/checks/checkcontextonreturn/server.go
Clean up the peer on Requests and Closes from begin. It disables authorization and recvfd 
https://github.com/networkservicemesh/integration-k8s-kind/pull/1013
=> Add peer cleanup on Requests and Closes from begin

pkg/networkservice/common/authorize/server.go, pkg/networkservice/common/authorize/server_test.go
Authorize still works on Close requests from begin. This PR adds additional check for this edge case.
https://github.com/networkservicemesh/integration-k8s-kind/pull/1013
=> fix authorize

pkg/networkservice/common/mechanisms/kernel/client.go, pkg/networkservice/common/mechanisms/kernel/client_test.go, pkg/networkservice/common/mechanisms/kernel/option.go, pkg/networkservice/common/mechanisms/kernel/server.go, pkg/networkservice/common/mechanisms/kernel/server_test.go, pkg/tools/nanoid/generator.go, pkg/tools/nanoid/utils.go
Current iface naming format is `nsm%id`  in the main branch (release v1.13.1)
Previous iface naming format is `$networkServiceName-$id`
PR returns the previous iface name conversion to respond on https://github.com/networkservicemesh/sdk/issues/1589#issuecomment-2167448160
Closes https://github.com/networkservicemesh/sdk/issues/1589
=> Use network service for generating iface name on nse side

pkg/networkservice/common/netsvcmonitor/server.go, pkg/networkservice/common/netsvcmonitor/server_test.go
https://github.com/networkservicemesh/cmd-nsmgr/issues/675
https://github.com/networkservicemesh/cmd-nsmgr/issues/675
=> Fix potential leaks of nse/ns streams in case of lost close

go.mod, go.sum, pkg/networkservice/common/monitor/client_filter.go, pkg/networkservice/common/monitor/eventloop.go, pkg/networkservice/common/monitor/server.go, pkg/networkservice/common/monitor/server_test.go, pkg/networkservice/common/updatepath/client.go
=> Leak fixes

pkg/tools/pprof/pprof.go
Add sdk/pkg/tools/pprof
https://github.com/networkservicemesh/deployments-k8s/issues/12045
=> Add sdk/pkg/tools/pprof

go.mod, pkg/tools/prometheus/prometheus.go, pkg/tools/prometheus/server.go
Added a new server that can be utilized to expose Prometheus metrics on via http or https.
https://github.com/networkservicemesh/sdk/issues/1652
=> Add an option to expose Prometheus metrics via http/s server

pkg/networkservice/common/begin/event_factory.go, pkg/networkservice/common/begin/event_factory_server_test.go, pkg/networkservice/common/begin/options.go, pkg/networkservice/common/begin/server.go, pkg/networkservice/common/begin/server_test.go, pkg/networkservice/common/dial/client.go, pkg/networkservice/common/dial/dialer.go
These changes should fix leaking interfaces on requests in case of small timeout. 
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/1133
=> Use a context with exteded timeout on Requests in begin

.github/workflows/release.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
Two additional dependencies in workflow need to be removed
1. `sdk` -> `cmd-nsc-init` (is extra for `sdk` -> `sdk-kernel` -> `sdk-sriov` -> `cmd-nsc-init` )
2. `sdk` -> `cmd-admission-webhook-k8s` (is extra for `sdk` -> `sdk-k8s` -> `cmd-admission-webhook-k8s` )
=> Delete extra dependencies from workflow

pkg/networkservice/common/discoverforwarder/server.go
Typo in server.go:
```panic("mseClient can not be nil")```
=> Fix typo in server.go

pkg/networkservice/chains/nsmgr/heal_test.go, pkg/networkservice/common/dial/dialer.go, pkg/networkservice/common/discoverforwarder/server.go
=> Add more mutexes in dial chain element to fix race conditions

pkg/tools/log/logruslogger/levelchange.go
Add a few additional checks to the setup according to the comments below
Though I'm not super confident whether these changes make it any better, but I'm out of ideas.
It might be worth reducing the array size to fixed 2, as there's not much else than SIGUSR1, and SIGUSR2 for usage.
Also checking whether the values are the same in the map came out a bit too long, not sure if worth it.
Also there's only a single log line indicating that this thing is disabled, it could be a bit confusing, if someone gets used to the feature and doesn't see any log messages when he sends a signal.
So not sure what do you think?
https://github.com/networkservicemesh/cmd-forwarder-vpp/pull/1171#issuecomment-2376939709
https://github.com/networkservicemesh/deployments-k8s/issues/12296
=> Add boundary check to SetupLogLevelChange

pkg/registry/common/memory/ns_server.go, pkg/registry/common/memory/ns_server_test.go
Use `NetworkSeviceResponse` instead of `NetworkService` in event channels in memory registry so registry clients can get and process `Delete` events.
https://github.com/networkservicemesh/sdk/pull/1676
=> Use NetworkServiceResponses instead of NetworkServices in memory registry

pkg/networkservice/common/timeout/server.go
https://github.com/networkservicemesh/cmd-forwarder-vpp/issues/1129
=> Fix context leak in `timeout` chain element

pkg/tools/opa/policy.go
Revert this [PR](https://github.com/networkservicemesh/sdk/pull/1624) because it significantly slows down the request processing time.
https://github.com/networkservicemesh/sdk/issues/1666
=> Revert "Fix some leaks in opa policies (#1624)"

go.mod, go.sum
`goleak` can cause panic while parsing stack trace. The fix has been provided in the commit: https://github.com/uber-go/goleak/commit/b62053be54d7ad632e413adc0947f535f087b0e1. This PR updates `goleak` to the lastest commit of `master` branch.
https://github.com/networkservicemesh/deployments-k8s/issues/12544
=> Update `goleak` to the lastest commit

pkg/networkservice/chains/nsmgr/heal_test.go
It looks like some of the failing unit tests just don't have enough test timeout
https://github.com/networkservicemesh/deployments-k8s/issues/12544
=> Increase timeout for all sandbox heal tests

pkg/registry/chains/client/ns_client.go, pkg/registry/chains/client/nse_client.go, pkg/registry/chains/client/option.go
We should not use **retry** and **heal** logic for discover endpoint on forwarder side https://github.com/networkservicemesh/sdk-vpp/blob/main/pkg/networkservice/chains/forwarder/server.go#L97-L110.
It can slow discover process in times.
=> add options for using custom heal/reetry clients for registry

pkg/networkservice/chains/nsmgr/vl3_test.go, pkg/networkservice/common/dial/dialer.go
https://github.com/networkservicemesh/sdk/issues/1695
=> fix `Test_NSC_ConnectsTo_vl3NSE`

pkg/networkservice/core/trace/server_test.go, pkg/networkservice/core/trace/traceconcise/common.go, pkg/registry/core/trace/traceconcise/common.go
Readd optinal trace condition to logObject
https://github.com/networkservicemesh/sdk/issues/1707
=> Readd optinal trace condition to logObject

.github/dependabot.yml, .github/workflows/automerge.yaml
This PR enables Dependabot in the repository to automatically check GitHub Actions versions weekly and create pull requests for any outdated dependencies found.
=> Enable dependabot for updating github actions

.github/workflows/automerge.yaml, .github/workflows/update-dependent-repositories-gomod.yaml
This PR disables the automerge workflow for pull requests opened by dependabot.
=> Disable automerge workflow for dependabot

pkg/tools/prometheus/server.go
This PR introduces an option to configure custom certificates for the Prometheus metrics server. Additionally, it includes support for automatic certificate renewal to ensure the server remains operational with valid certificates.
https://github.com/networkservicemesh/sdk/issues/1652
=> Support custom certificates in metrics server
